qbicc/qbicc

compiler/src/main/java/org/qbicc/graph/CheckCast.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/schedule/Schedule.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java

Using Schedule when copying nodes ensures that the nodes are processed before their dependencies.
Fixes #517

Use schedule in copier

---

compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/ClassInitializerRegister.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayBuilder.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayEmitter.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayTables.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

Original PR was https://github.com/qbicc/qbicc/pull/501, links broken when going public.  See that PR for initial reviews and discussion.
---
Related to #458
* Lower the class initialization status and function pointer to the `<clinit>` method into a new structure:
```
qbicc_clinit_state {
u8[typeid] clinitState;  // 0 or 1
void (i8 addrspace(1)*)*[typeid]// <clinit> function pointers
}
```
* Sketch out the class initialization protocol as defined in the JVMS
* Ensure the full set of <clinit> methods are enqueued
* Refactoring of emitting the `qbicc_typeid_array`
* Register `<clinit>` methods as entrypoints so they persist to code generation
* Emit the `qbicc_clinit_state` table

More <clinit> groundwork

---

compiler/src/main/java/org/qbicc/type/TypeType.java
plugins/conversion/src/main/java/org/qbicc/plugin/conversion/NumericalConversionBasicBlockBuilder.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

Walk the `qcc_typeid_array[typeid].interfaceBits` to find all the interfaces that are implemented by the current class.  This finds the full set of interfaces that a class implements.  Only interfaces that `ObjectModel.declares_default_methods(type_id)` actually need to be initialized.  This initializes the right interfaces but the ordering doesn't match the spec yet.
TypeType is now a WordType so it can be created at runtime from an integer.
Added some helper methods to print numbers to allow tracing class initialization.  They should be removed when we have a better way to trace runtime actions (JFR?).
Stubbed out `Object.notifyAll()` so the initialization state machine can use it before locks are fully supported.

Class init: support initializing interfaces

---

compiler/src/main/java/org/qbicc/type/definition/element/ExecutableElement.java
compiler/src/main/java/org/qbicc/type/definition/element/InitializerElement.java
compiler/src/main/java/org/qbicc/type/definition/element/InvokableElement.java
driver/src/main/java/org/qbicc/driver/Driver.java
main/src/main/java/org/qbicc/main/Main.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotGenerator.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/native/src/main/java/org/qbicc/plugin/native_/ConstantDefiningBasicBlockBuilder.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBindingTypeBuilder.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/HeapSerializer.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/ClassInitializingBasicBlockBuilder.java

This change fixes the constant ordering issue.  It's based on #531 so it's not as big as it looks... only the last two commits belong to this change.
This might provide a basis to simplify #530 by allowing clinits to be recursively compiled, and maybe re-enqueued as well.
Use this link to see just the two commits: a9e56d6...f305662

Compile clinit methods before anything else

---

machine/tool/clang/src/main/java/org/qbicc/machine/tool/clang/AbstractClangInvoker.java
machine/tool/clang/src/main/java/org/qbicc/machine/tool/clang/ClangCCompilerInvokerImpl.java
machine/tool/clang/src/main/java/org/qbicc/machine/tool/clang/ClangLinkerInvokerImpl.java

1. push -pthread option down to the compiler/linker invokers
2. only give -std, -pthread, -input-charset when source language is C

reduce clang warnings on MacOS

---

integration-tests/src/it/java/org/qbicc/tests/integration/SimpleAppTest.java
integration-tests/src/it/java/org/qbicc/tests/integration/SnippetsTest.java
integration-tests/src/it/java/org/qbicc/tests/integration/utils/NativeExecutable.java

Output looks like:
```
2021-06-09 10:42:13.756 INFO  [o.q.t.i.u.NativeExecutable] (run) Process(Arrays) standard output:
```
Found this to be useful when trying to diagnose which Snippet test failed.

Include test / snippet name in stderr & stdout output

---

machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/ArrayImpl.java

Output looks like:
```
@qbicc_typeid_array = global [189 x %T.struct.typeIds] [
%T.struct.typeIds zeroinitializer, ; 0
%T.struct.typeIds { i32 1, i32 1, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 1
%T.struct.typeIds { i32 2, i32 2, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 2
%T.struct.typeIds { i32 3, i32 3, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 3
%T.struct.typeIds { i32 4, i32 4, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 4
%T.struct.typeIds { i32 5, i32 5, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 5
%T.struct.typeIds { i32 6, i32 6, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 6
%T.struct.typeIds { i32 7, i32 7, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 7
%T.struct.typeIds { i32 8, i32 8, i32 0, [4 x i8] zeroinitializer, i32 0 }, ; 8
%T.struct.typeIds { i32 9, i32 9, i32 0, …
```

Format large arrays with one item per line and append item index

---

compiler/src/main/java/org/qbicc/type/TypeSystem.java
main/src/main/java/org/qbicc/main/Main.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/HeapOutputStream.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/HeapSerializer.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/Serializer.java
runtime/deserialization/src/main/java/org/qbicc/runtime/deserialization/DeserializationBuffer.java
runtime/deserialization/src/main/java/org/qbicc/runtime/deserialization/SerializationConstants.java
runtime/deserialization/src/test/java/org/qbicc/runtime/deserialization/TestDeserialization.java
runtime/main/src/main/java/org/qbicc/runtime/main/Main.java

Refactor heap serialization plugin to use a ByteBuffer
as the lowlevel output target.  This allows us to
select the endianness at compile time to match the
target platform.

Heap serialization: configurable endianness

---

machine/file/elf/src/main/java/org/qbicc/machine/file/elf/ElfHeader.java
machine/file/elf/src/main/java/org/qbicc/machine/file/elf/ElfObjectFileProvider.java
machine/file/macho/src/main/java/org/qbicc/machine/file/macho/MachOObjectFile.java
machine/file/object/src/main/java/org/qbicc/machine/object/ObjectFile.java
machine/probe/src/main/java/org/qbicc/machine/probe/CProbe.java

This patch extends CProbe to allow it to get the actual function name
if the function exposed as an API is just a C macro.
This is the case with many of libunwind APIs.
For example `unw_init_local` is defined as a macro which expands to a
platform specific function.
To get the actual function name CProbe would emit a file like:
void * fn_address0 = <function_to_probe>;
Object file for this code would contain entry in symbol table for
`fn_address0` and its offset in data section.
For the same offset there would be an entry in the relocation section
and the symbol corresponding to that entry would give us the actual
function name.

Implement CProbe for functions

---

compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
integration-tests/src/it/java/org/qbicc/tests/integration/SnippetsTest.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayTables.java

Dave correctly pointed out that the original implementation only
walked the directly implemented interfaces of the target class
and its superclasses.
It was missing the walk of the interfaces super-interfaces.
I've now corrected the implementation and tightend it to only visit
each interface once.

Fix forEachInterfaceFullImplementedSet() to actually walk superinterfaces

---

compiler/src/main/java/org/qbicc/graph/ActionVisitor.java
compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/ClassInitCheck.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
main/src/main/java/org/qbicc/main/Main.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/LowerClassInitCheckBlockBuilder.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayTables.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/LowerVerificationBasicBlockBuilder.java
runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

With this commit, runtime class initialization works.  The "is_initialized()" checks are inserted before `get/putstatic` and `invokestatic` bytecodes as well as at `new` bytecodes.
The state machine correctly marks classes as initialized and everything seems to work OK with it.

Enable runtime class initialization

---

main/pom.xml
main/src/main/java/org/qbicc/main/Main.java
plugins/core-classes/pom.xml
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
plugins/pom.xml
pom.xml

This is a cleanup to move the non-layout related code from `Layout`, thereby simplifying that class substantially.  Also adds a number of convenience methods.  The initial PR doesn't change existing usages of the methods on `Layout` which now bridge to `CoreClasses`, so as to minimize disruption.  We can clean them as we go, and then do a final cutover sometime later.

Introduce core classes plugin; remove corresponding code from Layout

---

compiler/src/main/java/org/qbicc/context/CompilationContext.java
compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
driver/src/main/java/org/qbicc/driver/Driver.java
driver/src/main/java/org/qbicc/driver/ElementBodyCopier.java
driver/src/main/java/org/qbicc/driver/ElementBodyCreator.java
driver/src/main/java/org/qbicc/driver/ElementVisitorAdapter.java
main/src/main/java/org/qbicc/main/Main.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/FunctionLoweringElementHandler.java

This is an API cleanup and does not add significant functionality.  It was just a long-standing todo.

Generalize member copying and move function lowering to the lowering plugin

---

plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTableBuilder.java
plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTableEmitter.java
plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java

Switch from directly indexed itables to searched itables to implement
invokeinterface.  This results in a slightly slower dispatch sequence,
but drops the data space consumed by interface dispatch data
structures from over 2MB to about 85KB for a trivial program.
Fixes #587.

invokeinterface: use searched itables

---

main/src/main/java/org/qbicc/main/Main.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
plugins/native/pom.xml
plugins/native/src/main/java/org/qbicc/plugin/native_/InternalNativeTypeResolver.java
plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeTypeBuilder.java
plugins/native/src/main/java/org/qbicc/plugin/native_/StructMemberAccessBasicBlockBuilder.java

Added a type resolver that converts internal native type (a type that
is annotated with @internal) to CompoundType.
Also added a basic block builder that transforms access to native type's
fields.

Convert internal native structs to CompoundType

---

driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java

This change uses the virtualFunctions map for the getVirtualFunctions().

Use a proper map for getVirutalFunctions

---

compiler/src/main/java/org/qbicc/type/definition/ModuleDefinitionImpl.java

This fix uses the requires_version_index in the requires table of the module attribute to get the version of the specified module.

Get an entry at requires_version_index

---

machine/llvm/src/main/java/org/qbicc/machine/llvm/StructType.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/StructTypeImpl.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java

Making struct types member names available in LLVM IR would make is much easier to read the IR. 
I tried to use `Commentable` interface to add comments to `members` of `StructTypeImpl`, but it proved to be too complicated without getting the desired result.
In the end I resorted to this much simpler change which just meets the purpose.
Now the struct types in LLVM IR look like this:
```
%T.java.lang.InstantiationException = type { i32 ; typeId
, i32 ; depth
, i8 addrspace(1)* ; backtrace
, i8 addrspace(1)* ; detailMessage
, i8 addrspace(1)* ; cause
, i8 addrspace(1)* ; stackTrace
, i8 addrspace(1)* ; suppressedExceptions
}
```
And it shows you the padding bytes as well:
```
%T.java.util.StringJoiner = type { i32 ; typeId
, i32 ; size
, i8 addrspace(1)* ; prefix
, i8 addrspace(1)* ; …
```

Display struct type's member names in the comments

---

machine/file/elf/src/main/java/org/qbicc/machine/file/elf/ElfObjectFileProvider.java
machine/file/macho/src/main/java/org/qbicc/machine/file/macho/MachOObjectFile.java
machine/file/object/src/main/java/org/qbicc/machine/object/ObjectFile.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java

https://llvm.org/docs/StackMaps.html#stack-map-section states Stack Map section name is different for ELF and MachO file formats. This PR makes changes to use the correct name for the Stack Map section based on the file format.

Use StackMap section name specific to objectfile format

---

machine/file/macho/src/main/java/org/qbicc/machine/file/macho/MachOObjectFile.java

The original implementation was using the Segment->Section mapping
and was trying to use the same name for both the segment and the
section.
This failed when looking up the `__llvm_stackmaps` section on macho
as the segment is named `__LLVM_STACKMAPS`.
New algorithm searches the segments list until it finds one of the
matching name and uses that to provide an org.qbicc.machine.object.Section
instances.
Co-authored-by: Ashutosh Mehra <asmehra@redhat.com>

Search all sections in getSection() for named one

---

compiler/src/main/java/org/qbicc/graph/CmpAndSwap.java
compiler/src/main/java/org/qbicc/type/CompoundType.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/ExtractValueImpl.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java

LLVM literal and identified structure types are not interchangeable. A literal type is needed to correctly interpret the return value of cmpxchg.
change relates to: https://github.com/qbicc/qbicc/pull/619

Lower literal structs for extractvalue

---

compiler/src/main/java/org/qbicc/type/TypeSystem.java
main/src/main/java/org/qbicc/main/Main.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java
runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java

Fixes a GPF when throwing exceptions on BigSur because the unwindException struct element of the VMThread object was only being aligned to 8 bytes, not 16 as required by the libunwind specification.

Ensure 16 byte alignment of struct_UnwindException

---

compiler/src/main/java/org/qbicc/graph/CmpAndSwap.java
compiler/src/main/java/org/qbicc/type/TypeSystem.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/LLBuilder.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/BuilderImpl.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/CmpAndSwapImpl.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/op/CmpAndSwap.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

Lowers the CmpAndSwap value to the LLVM IR cmpxchg instruction. 
cmpxchg returns a "literal" structure type and I believe only "identified" llvm structure types are currently supported. The next step will be to correctly lower `extractvalue` to use a literal structure so the result of cmpxchg can be accessed. 
update: https://github.com/qbicc/qbicc/pull/620

CompareAndSwap lowering

---

main/src/main/java/org/qbicc/main/Main.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
plugins/intrinsics/pom.xml
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/serialization/pom.xml
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ClassObjectSerializer.java
runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

Initial steps; should be enough for executing static synchronized methods using the nativeObjectMonitor field of the appropriate class object.
- Emit the array of j.l.C instances indexed by typeId
- Implement VM_Helpers.classof_from_typeid
- Add compiler pass to "serialize" j.l.C instances for all initialized types
- Initialize a couple of the instance fields (name, id); leave the rest zero initialized.

Serialization of java.lang.Class instances

---

plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java

An invokevirtual whose target is a native method cannot be converted
to an unconditional throw of an UnsatisfiedLinkError because the
virtual method may be overriden. Tested against the class library
at 8311cc4b2 (before the addition of a non-native Object.toString())
and verified that with this fix I see the same 4MB growth in final
executable size that I saw when defining a non-native Object.toString.

Bug fix in conversion of invokes to linktime errors

---

driver/src/main/java/org/qbicc/driver/ElementInitializer.java
main/src/main/java/org/qbicc/main/Main.java
plugins/conversion/src/main/java/org/qbicc/plugin/conversion/LLVMCompatibleBasicBlockBuilder.java

Allowing compilation to complete even with failing class init will allow us to move more quickly with getting something working.  The most expedient way to make this work is to disable run time init when build time init is enabled, but this is not strictly correct.  If a class fails to initialize during build, then any class init check should be replaced with a throw of an exception-in-initializer error (which will result in pruning much of the program graph).
The next step would be to determine how the build and run time init modes could mix - if they can at all.

Make class initialization failure a warning... for now

---

compiler/src/main/java/org/qbicc/interpreter/Vm.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ObjectLiteralSerializingVisitor.java

Support serialization of VmObject instances to the initial heap.
Currently being used to serialize String literals and java.lang.Class
instances.  Should support arbitrary VmObject graphs as soon as
we manage to get them all the way to the backend.

Convert BuildTimeHeap to using VmObject

---

interpreter/pom.xml
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
main/src/main/java/org/qbicc/main/Main.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java

Three main changes, all conditional on builtTimeInit being true:
1. Extend the interpreter to log the instantiated types with RTAInfo (buildTimeInit == true implied)
2. Process the logged types as reachable at the beginning of each RTA analysis phase
3. Do not enqueue the `<clinit>` method as reachable
I want to take a closer look in the morning, but this seems to be doing something reasonable at first glance at the -rta-debug logs.

extend reachability analysis to model build time initialization

---

compiler/src/main/java/org/qbicc/interpreter/VmClass.java
compiler/src/main/java/org/qbicc/interpreter/VmPrimitiveClass.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmPrimitiveClassImpl.java
plugins/lowering/pom.xml
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ClassObjectSerializer.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ObjectLiteralSerializingVisitor.java

Serialize the values that the interpreter has computed for static fields.
Fix several bugs in VMBuildTimeHeap exposed by actually serializing interesting object graphs.

Serialize interpreter heap

---

interpreter/pom.xml
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java

Replace the conservative assumption that all types that were instantiated in the interpreter's heap are reachable with the proper optimistic algorithm that instead traces the portions of the heap that can be reached from static fields as those static fields become reachable. We will inspect each object in the interpreter heap at most once during this analysis (once an object is reachable from one static, it doesn't matter if it is also reachable from other statics).
This PR builds on top of #667.   The results seem almost too good to be true, so I decided to not incorporate this change into #667 in case I messed something up and didn't see it at first...

Improve reachability analysis of interpreter heap

---

compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/UnsafeHandle.java
compiler/src/main/java/org/qbicc/graph/ValueHandleVisitor.java
compiler/src/main/java/org/qbicc/graph/ValueHandleVisitorLong.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/ObjectAccessLoweringBuilder.java

Keep a high-level representation of the ref+offset pointers introduced
by Unsafe during the ADD/ANALYZE phases to simplify analysis and
build-time interpretation.

add an UnsafeHandle for ref+offset handles

---

plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

A class may have multiple instance fields with the same name...

bug fix: do not look up instance fields by name

---

plugins/dot/src/main/java/org/qbicc/plugin/dot/DotGenerator.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java

Improve CPU utilization by further limiting the size/complexity of DOT graphs and running DOT tasks in parallel; also, quiet the warning output when a DOT graph is too big

Improve CPU utilization of DOT generation

---

compiler/src/main/java/org/qbicc/interpreter/Vm.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

Just an incremental step over what's already there. Next step would be finding a solution for starting them up at run time (see #764 for more discussion).

Track threads started in initializers and make them available

---

machine/probe/src/main/java/org/qbicc/machine/probe/CProbe.java
plugins/native/src/main/java/org/qbicc/plugin/native_/ConstantDefiningBasicBlockBuilder.java
plugins/native/src/main/java/org/qbicc/plugin/native_/ExternExportTypeBuilder.java
plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
plugins/native/src/main/java/org/qbicc/plugin/native_/ProbeUtils.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java

Adds an `@undef` annotation and ensures that define/undef come before include; also makes sure that members can (for the most part) override enclosing class annotations by ordering their define/undefs after the enclosing type

Add @undef annotation, C probe fixes

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java

Refactoring to remove code duplication with `ObjectModel` helpers

Refactor j.l.Class intrinsics to invoke ObjectModel helpers

---

compiler/src/main/java/org/qbicc/interpreter/InterpreterHaltedException.java
compiler/src/main/java/org/qbicc/interpreter/Thrown.java
compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
driver/src/main/java/org/qbicc/driver/ElementInitializer.java
integration-tests/src/it-in/snippets/ClassInit.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmInvokableImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java

Switch over to always using build time init.  The run time init code is preserved until we solidify our strategy on split initialization; it is my feeling that the easiest way forward will be to supplement classes with a run time init stub in some way. I'll come up with a more formal proposal for the discussion board.
May require #759 and #757 in order to compile correctly.

Make build time initialization always-on

---

main/src/main/java/org/qbicc/main/Main.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java

Simplify reachability analysis by removing conditional logic for
processing <clinit> methods at either build time or runtime.

post #760 cleanup of Reachability

---

driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/RuntimeMethodFinder.java
plugins/intrinsics/pom.xml
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
plugins/methodinfo/pom.xml
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/CallSiteInfo.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataTypes.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodInfo.java
runtime/main/pom.xml
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackFrameCache.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackFrameVisitor.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackWalker.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/MethodData.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/StackFrameVisitor.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/StackWalker.java

Add stack walker and provided intrinsics to access method data.
I have addressed the review comments mentioned in https://github.com/qbicc/qbicc/pull/709 viz:
1. Moved stack walker to runtime main module
2. Updated stack walker to handle frames for inlined methods (although it is not tested)

Add stack walker and intrinsics to access method data

---

plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java

Some of the methods like `VMHelpers#raiseUnsatisfiedLinkError`
may be referenced post lower phase only. Therefore if we rely on manually
enqueuing such methods, then it has to be done in each phase.
Instead its better if we register them as entry points so that they get
queued in each phase.

Add VMHelpers methods that raise an exception as entry points

---

runtime/unwind/src/main/java/org/qbicc/runtime/unwind/LibUnwind.java

The unwind functions we want are in the system libs; adding an
extra flag just confuses the linker because there is no libunwind.

Don't add -lunwind when targeting macos

---

examples/helloworld/hello/world/Main.java

We don't need the dependency, and having it actually is a problem for doing
```
--boot-path-append-file $(jbang info classpath examples/helloworld/hello/world/Main.java)
```
because `--boot-path-append-file` doesn't support currently support adding a `:` separated list of files.

No longer need qbicc-runtime-api dep in hello.world example

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataTypes.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodInfo.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/MethodDataStringsSerializer.java
runtime/main/pom.xml
runtime/main/src/main/java/org/qbicc/runtime/main/Main.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackWalker.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/MethodData.java

~Do not generate method data for methods marked as `Hidden` so that
they are not included in stack trace.~
Store method modifiers in method data so that the frames for methods
marked as hidden can be skipped when creating stack trace.
Annotate following methods with `Hidden` annotation:
- `org.qbicc.runtime.Main#main`
- `org.qbicc.runtime.stackwalk.JavaStackWalker#getFrameCount`
- `org.qbicc.runtime.stackwalk.JavaStackWalker#walkStack`
Also exclude exception constructors and `Throwable.fillInStackTrace`
method from stack trace

Exclude Hidden methods from stack trace

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataTypes.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodInfo.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/MethodData.java

MethodData stores typeId and that can be used to get the class name,
instead of storing pointer to class name String object explicitly.

Use typeId in MethodData to get class name

---

compiler/src/main/java/org/qbicc/graph/PointerHandle.java

A minor oversight.  But we need a better solution for this TBH.  Maybe program objects should have a full set of modifier flags.

Propagate NoReturn/NoSideEffect info from functions to pointer handles

---

plugins/dot/src/main/java/org/qbicc/plugin/dot/DotGenerator.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java

Closes #806
* This avoids confusion when files are partially written,
and you think the dot node visitor has a bug instead.
* Also fixed some formatting on local variables.
* Too big graphs take too long to convert to svg,
so discarding option to add a system property to expand
the configured counts in dot node visitor.

Delete files if they're too big

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java

This small optimization changes a bitcast in `utf8z` to a `getelementptr` to the first element of the array.

Avoid bitcast to the first element of the array

---

compiler/src/main/java/org/qbicc/graph/InsertElement.java
compiler/src/main/java/org/qbicc/graph/InsertMember.java
compiler/src/main/java/org/qbicc/graph/Value.java
compiler/src/main/java/org/qbicc/graph/literal/ArrayLiteral.java
compiler/src/main/java/org/qbicc/graph/literal/ByteArrayLiteral.java
compiler/src/main/java/org/qbicc/graph/literal/CompoundLiteral.java
compiler/src/main/java/org/qbicc/graph/literal/ZeroInitializerLiteral.java
compiler/src/main/java/org/qbicc/type/TypeSystem.java
compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBasicBlockBuilder.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeTypeResolver.java
plugins/native/src/main/java/org/qbicc/plugin/native_/PointerTypeResolver.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java

This works by fixing a few longstanding problems:
* Arrays of native types are actual array values instead of pointers to them
* Fully implement extraction and insertion of literal array and structure values
* Be less strict about handling values of incomplete type
* Add optimizations which can optimize away array values for vararg calls
After this patch, things like `printf(utf8z("The size of an int is %d\n"), word(sizeof(c_int.class)))` will work as expected.
As an aside, this should significantly alleviate at least some of the issues with pointer dereferencing by eliminating a class of invalid handle types.
/cc @theresa-m

Complete vararg calling support

---

main/src/main/java/org/qbicc/main/Main.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/StaticChecksBasicBlockBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
plugins/native/src/main/java/org/qbicc/plugin/native_/PointerBasicBlockBuilder.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/GotoRemovingVisitor.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java

Introduce optimizations which:
* Convert bitcasts to the same type as the first element or member of an array or structure to a GEP construct
* Allow `Neg` to be canonical for integer negation
* Transform `If`->`Goto`x2->`Phi` diamonds to `Select`
* Improve the quality and accuracy of simple transformations in the simple optimizer
* Remove an invalid conversion
* Introduce some new simple optimizations
* Remove the old unused pointer arithmetic constructs
Introduce static verification BBB which prevents invalid or buggy constructs from being emitted.  Also, remove some dead code.

Multiple optimization and verification improvements

---

machine/tool/api/src/main/java/org/qbicc/machine/tool/CToolChain.java
machine/tool/api/src/main/java/org/qbicc/machine/tool/ToolProvider.java

Looks for compilers in path preference order instead of random service loader order.  Also, accept the `CC` env variable as the highest preference for C compiler.

Fix compiler selection problems

---

main/src/main/java/org/qbicc/main/Main.java

According to https://picocli.info/#_negatable_options, negatable options which default to `true` should be specified in their negative form.  Otherwise we end up with the options having the correct default but opposite meaning when specified.

Fix negatable options that default to `true`

---

compiler/src/main/java/org/qbicc/graph/AbstractBinaryValue.java

Ideally we'd do this in a more object-oriented manner, however the commutative binary operations do not always have a superclass slot available, and it's not really possible to correctly implement equals/hashCode as interface default methods.  This gets the job done and keeps the mess localized.

Commutative equals/hashCode for commutative binary values

---

compiler/src/main/java/org/qbicc/graph/AbstractBooleanCompare.java
compiler/src/main/java/org/qbicc/graph/And.java
compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/BooleanValue.java
compiler/src/main/java/org/qbicc/graph/CommutativeBinaryValue.java
compiler/src/main/java/org/qbicc/graph/Comp.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/If.java
compiler/src/main/java/org/qbicc/graph/InstanceOf.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/Or.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/Value.java
compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
plugins/optimization/pom.xml
plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java
plugins/optimization/src/test/java/org/qbicc/plugin/opt/TestSimpleOptBasicBlockBuilderBooleanLogic.java
pom.xml
test-utils/pom.xml
test-utils/src/main/java/org/qbicc/test/AbstractCompilerTestCase.java

* Introduce a general unit test utility
* Introduce `Comp` ones-complement node, use it as canonical form for boolean inversion
* Introduce several transformations to optimize and/or canonicalize boolean forms
* Allow any value to have a value-if-true/false
* Front-load `InstanceOf` value-if-true (allows optimizations to simplify it)
* Add the start of unit tests for individual optimization transformations using the unit test utility

A number of improvements to boolean values & a unit test fwk

---

plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java

In conjunction with an experimental/not-quite-working-yet DFA optimization, this eliminates multiple switches from the `java.util.regex.Pattern` class.

Constant switch condition opt

---

compiler/src/main/java/org/qbicc/graph/ActionVisitor.java
compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/InitCheck.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/LowerClassInitCheckBlockBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/LowerVerificationBasicBlockBuilder.java

The idea is to begin migrating the `InitCheck` node to be per-initializer rather than per-class. Doing this rename early will simplify the diff of those changes.

Rename `ClassInitCheck` to `InitCheck`

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

Initialize java.lang.ref.Reference early to avoid deadlock

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmInvokableImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmThreadImpl.java

This and #866 are predecessors to `park`/`unpark` in the interpreter.

Always bind current thread during invocations

---

.github/workflows/maven.yml
compiler/src/main/java/org/qbicc/context/Diagnostic.java
compiler/src/main/java/org/qbicc/context/DiagnosticContext.java
main/pom.xml
main/src/main/java/org/qbicc/main/ClassPathEntry.java
main/src/main/java/org/qbicc/main/Main.java
main/src/main/java/org/qbicc/main/QbiccMavenResolver.java
main/src/main/java/org/qbicc/main/QbiccServiceLocator.java
main/src/main/java/org/qbicc/main/QbiccWagonProvider.java
pom.xml

This allows us to have an accurate class path in the same order it was specified on the command line. It's also much faster (but it's possible that the Maven Central repository isn't correctly configured; we'll see how CI likes it).
This also will allow us to build an app class path which automatically excludes any artifacts that are already on the boot class path.

Drop ShrinkWrap Resolver in favor of Aether

---

compiler/src/main/java/org/qbicc/context/CompilationContext.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/RuntimeMethodFinder.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/LowerClassInitCheckBlockBuilder.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
plugins/objectmonitor/pom.xml
plugins/objectmonitor/src/main/java/org/qbicc/plugin/objectmonitor/ObjectMonitorBasicBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java

Deprecate the old methods, but leave them in place in case they are being used in people's branches.

Move runtime method lookup from CompilationContext to RuntimeMethodFinder

---

runtime/main/src/main/java/org/qbicc/runtime/main/Monitor.java

Replaces #874.  Only introduce the new API; wait for release cadence before doing any more.

Introduce pure-Java Monitor implementation

---

interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
main/src/main/java/org/qbicc/main/Main.java
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/ArrayLengthBasicBlockBuilder.java
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/BasicInitializationBasicBlockBuilder.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java

A fairly minimal change that fixes the double-initialization problem (https://github.com/qbicc/qbicc/pull/904#issuecomment-985192707).
I'm tempted to attempt a cleanup where we push `manuallyInitialize` inside of the implementation of VmClass.newInstance to DRY things up... any a priori reason that won't work?

restructure header initialization to avoid doing it twice

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/RuntimeMethodFinder.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/LowerClassInitCheckBlockBuilder.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
plugins/objectmonitor/src/main/java/org/qbicc/plugin/objectmonitor/ObjectMonitorBasicBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
runtime/main/src/main/java/org/qbicc/runtime/main/CompilerIntrinsics.java
runtime/main/src/main/java/org/qbicc/runtime/main/Monitor.java
runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/MethodData.java

There should be no semantic change here; just lots of methods being moved and/or renamed.

use camelCase names for runtime helper methods and intrinsics

---

compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/element/FieldElement.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/core-classes/pom.xml
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
plugins/lowering/pom.xml
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/ThrowExceptionHelper.java

This replaces all but one usage of `injectField` with the patcher. The main difference here is that the injected fields will always be on the target class, instead of being added late, thus the interpreter doesn't need to have special hooks to access them.

Use Patcher instead of injectField

---

compiler/src/main/java/org/qbicc/interpreter/VmClass.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmObjectImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmThrowableImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/StaticFieldLoweringBasicBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

This PR introduces changes which:
* Make layout (nearly) 100% consistent between build and run time
* Opens up the `VmClass.registerInvokable` API
* Lowers static fields to structures again, in order to facilitate `Unsafe.staticFieldBase`
* Removes obsolete `Class.cast` intrinsic
* Add `Class.isInstance` support to the VM (not to run time though)
* Fix a couple of problems and missing features in reflective field and method enumeration
* Change support for `objectFieldOffset` and friends to yield an exact offset, but be build-time only - fields whose offsets are observed are marked as `I_ACC_PINNED`, to allow future `LOWER`-time field deletion and reshuffling

Build-time-complete layout

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java

This is a predecessor to using the new access modes to produce atomic and non-atomic memory access methods on `ptr`.

Move native intrinsics to a separate class for clarity

---

plugins/main/src/main/java/org/qbicc/plugin/main_method/AddMainClassHook.java

Motivated by the test program below, where `qbicc` failed compilation because it was convinced that `printIt` was the main method.
```public class NewArray {
static Object alloc(int size) {
return Array.newInstance(String.class, size);
}
static void printIt(String[] s) {
System.out.println(s[0]+" "+s[1]);
}
public static void main(String[] args) {
Object x = alloc(5);
String [] y = (String[])x;
y[0] = "Hello";
y[1] = "World";
printIt(y);
}
}
```

fix bug in main method finder

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java

Forgot to convert from Java's (src, dst) convention to C's (dst, src).

bug fix in copyInstanceField intrinsic

---

compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/MemberSelector.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
pom.xml
runtime/api/pom.xml
runtime/api/src/main/java/org/qbicc/runtime/CNative.java

This is a replacement for the unworkable `Deref` concept.
Allow a member to be selected, like this:
```java
struct_foo_ptr my_ptr = ...;
int_ptr memberPtr = addr_of(my_ptr.sel().member);
```
It's not quite as elegant but it is concise.

Introduce support for member selectors

---

.github/ISSUE_TEMPLATE/bug_report.md

There must have been a unicode fix of some sort on GitHub recently...

Fix bug issue template

---

plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBasicBlockBuilder.java

This is required for qbicc/qbicc-class-library#68.

Allow things to be cast to `word` and `object` safely

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java

Realized the only time this warning was firing anymore was for `_qbicc_bound_thread`, so we can eliminate it by not trying to trace the build-time initialization initial value of thread local fields.

Remove obsolete workaround for "missing" static fields

---

plugins/patcher/src/main/java/org/qbicc/plugin/patcher/PatchedTypeBuilder.java

The conditional annotation values `when` and `unless` were being ignored for injected members.

Only inject members if the condition passes

---

compiler/src/main/java/org/qbicc/type/definition/element/FieldElement.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
runtime/api/src/main/java/org/qbicc/runtime/SerializeAsZero.java
runtime/api/src/main/java/org/qbicc/runtime/SerializeBooleanAs.java
runtime/api/src/main/java/org/qbicc/runtime/SerializeFloatingPointAs.java
runtime/api/src/main/java/org/qbicc/runtime/SerializeIntegralAs.java

Cover two basic cases of replacing a field with a zero-initializer and replacing an integral field with a constant value (eg -1 for FileDescriptor.fd).
Not that attached to the actual names of the annotations, so happy to adjust if there are suggestions.
Thought about supporting Float, Double, and Boolean constants as well but don't know if we have a motivating example yet.

Annotations for serialization replacement

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmInvokableImpl.java

Cuts down some of the noise (flags 180 candidates instead of 680).

disable JIT candidate message

---

compiler/src/main/java/org/qbicc/graph/CmpAndSwap.java
compiler/src/main/java/org/qbicc/graph/ExtractMember.java
compiler/src/main/java/org/qbicc/graph/MemberOf.java
compiler/src/main/java/org/qbicc/type/CompoundType.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java

Structures are not correctly initialized (zeroed) or copied at present when there are members we do not know about (they exist in the padding space).  Furthermore there are several bugs around the ability to load and store structure and array values.
This series of commits adds a facility to get a padded member list for a `CompoundType`. The padded member list is used to load and store structure members piecemeal so that our atomicity guarantees can be maintained even in the face of members we do not know about.  We insert 64-bit integer padding whenever possible, and fall back to smaller padding sizes only to fill in unaligned spaces.
The padded member list is then also used to replace code in the LLVM back end which had the same job.  The previous padding code always used byte arrays, …

Fix padding-related problems

---

plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

LLVM is expecting an integer literal of the right type, not true/false.

fix serialization for SerializeAsBoolean annotated fields

---

plugins/conversion/src/main/java/org/qbicc/plugin/conversion/NumericalConversionBasicBlockBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMIntrinsics.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java

This allows `NumericalConversionBasicBlockBuilder` to be repeatable per #951.

Use conversion methods for floating point to integer conversions

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java

Instead of having to do `value.byteValue() & 0xff` you can do `value.ubyteValue()` for example.

Convenience methods to get unsigned byte, short, and int values

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/MethodData.java

It papers over another problem which is that an implicit cast from (small) type_id to short integer results in a `bitcast` of `i16` to `i16` at the LLVM level, so that would need investigating at some point.  But, this solution slightly improves the existing code anyway so we can solve the other later.

One more fix for small type IDs

---

plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java
runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java

Support annotation multiplicity for the `@align` attribute. Add (and use) `@align_as` attribute which allows the alignment of a type to be specified in terms of another type, like in C.

Some alignment fixes and improvements

---

main/src/main/java/org/qbicc/main/Main.java
main/src/main/resources/logging.properties
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

Just some basic stuff: Here's what it does right now.
```
[D] (org.qbicc.plugin.serialization.stats) LOWER: The initial heap contains 40,904 objects.
[D] (org.qbicc.plugin.serialization.stats) LOWER: The types with more than 5 instances are: 
[D] (org.qbicc.plugin.serialization.stats) LOWER:   14,017 instances of L[B;
[D] (org.qbicc.plugin.serialization.stats) LOWER:   13,840 instances of Ljava/lang/String;
[D] (org.qbicc.plugin.serialization.stats) LOWER:    1,758 instances of Ljava/lang/Class;
[D] (org.qbicc.plugin.serialization.stats) LOWER:    1,651 instances of Ljava/util/concurrent/ConcurrentHashMap$Node;
[D] (org.qbicc.plugin.serialization.stats) LOWER:    1,509 instances of L[L;
[D] (org.qbicc.plugin.serialization.stats) LOWER:    1,231 instances of Ljava/util/HashMap$Node;
[D] …
```

add reporting of a few basic statistics of the serialized heap

---

compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/interpreter/VmStaticFieldBaseObject.java
compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
compiler/src/main/java/org/qbicc/type/definition/DelegatingDefinedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFileImpl.java
compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmPrimitiveClassImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmStaticFieldBase.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/AbstractFunction.java
plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
plugins/reflection/pom.xml
plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java
plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectionIntrinsics.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/ClassLoadingBasicBlockBuilder.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java

Implements a number of features around method handles and hidden classes, and fixes a couple of side issues like improving the `toString` implementation of `VmClassImpl` and some filename and function name handling problems on the LLVM side.
The number of warnings should be generally reduced, though there are still known issues.  In any event, this seems like a reasonable checkpoint (assuming CI passes) as I continue to work through this.
Hidden classes are written with a file name like `org/foo/bar/Baz~123.ll` where `123` is the sequence number of the hidden class.  Since not all classes remain alive, there may be gaps in the sequence numbers of the classes that actually make it to `GENERATE`.

Method handles progress

---

plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java

Small improvement that makes it much easier to see what is happening in the .ll files
The method name gets put in the comment field in the table declaration and at the call site (when we load the function pointer from the struct member).

include method name in itable/vtable member name

---

plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBasicBlockBuilder.java

It's not clear exactly what semantics we want, but I think we probably want to allow static helper methods to be defined in $_native classes.  If so, then we need to allow those helpers to be resolved without denativing the owning class.
The example that motivated this change is https://github.com/qbicc/qbicc-class-library/blob/1bf1162aac92b5a57c3d459435018a257862a6f8/java.base/src/main/java/java/util/TimeZone%24_native.java#L26.  Without this fix, this invoke won't be resolved correctly.
I think the only alternative is to force helper methods to be defined in separate classes, which is certainly possible, but feels awkward.

Allow $_native classes to also contain static helper methods

---

compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java

Saves some typing and can reduce excessive lambda creation.

Add name-based requireSingleMethod

---

driver/src/main/java/org/qbicc/driver/GraphGenConfig.java
integration-tests/src/it/java/org/qbicc/tests/integration/utils/Qbicc.java
main/src/main/java/org/qbicc/main/Main.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotGenerationContext.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotGenerator.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
plugins/optimization/pom.xml
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/ConnectionGraph.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/ConnectionGraphDotGenerator.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/ConnectionGraphDotVisitor.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisDotGenerator.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisDotVisitor.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisInterMethodAnalysis.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisIntraMethodBuilder.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisOptimizeVisitor.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisState.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeValue.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/TooBigException.java
plugins/optimization/src/test/java/org/qbicc/plugin/opt/ea/EscapeValueTest.java

This PR replaces #932, to which the following changes have been applied:
1. If the compiler graph contains node types not yet handled by EA, any new allocations in the data flow graph from the unhandled nodes have their escape value switched to global escape. As mentioned in #932, this is done to err on the side of safety. This should handle all feedback regarding unhandled graph node types.
2. `DotNodeVisitor` can now be hooked with delegating node visitors to further decorate nodes. EA uses this mechanism to colour `New` nodes according to their escape value. Also, given EA's two-phase nature (intra method analysis and inter method analysis), I've enhanced the dot generator to produce two dot files for the analysis phase: `analysis-intra.dot` and `analysis-inter.dot`. This way, we can …

Escape Analysis v2

---

compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/StaticMethodPointerHandle.java
compiler/src/main/java/org/qbicc/graph/ValueHandleVisitor.java
compiler/src/main/java/org/qbicc/graph/ValueHandleVisitorLong.java
compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
compiler/src/main/java/org/qbicc/graph/literal/LiteralFactory.java
compiler/src/main/java/org/qbicc/graph/literal/PointerLiteral.java
compiler/src/main/java/org/qbicc/pointer/IntegerAsPointer.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
main/src/main/java/org/qbicc/main/Main.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/MemberPointerCopier.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

Add more support for manipulating pointer values in the interpreter, and ensure that pointers to static methods and fields can be properly lowered, including reachability support.

Further pointer support

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java

This helps greatly with debugging method handles.

Temporarily emit runtime-generated classes

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java

present in Java11, but removed in Java17.

remove obsolete Unsafe intrinsics

---

interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

Enough support for native memory idioms to allow us to interpret `NativeBuffers.copyCStringToNativeBuffer` successfully.

interpreter support for unsafe memcpy

---

main/src/main/java/org/qbicc/main/Main.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMDefaultModuleCompileStage.java

The llvm compilation of the generated .ll files represents about 75% of total wall clock compilation time. Allow the user a way to skip this stage if they are only interested in the generated .ll files (and not the actual executable).

add command line option to disable llvm compilation of output files

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

I admit I had this in the back of my mind when I made the backing array accessible from `VmArray`.

Implement fast invoker for System.arraycopy

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

Just use the definition that is already on hand.

Fix a bug where hidden classes cannot load themselves by name

---

compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java

Every time a signature-polymorphic method reference is encountered, redirect the reference to an element which is a copy of the original method but with a type which matches the call site type. Cache by type.

Expand resolution of signature-polymorphic methods

---

compiler/src/main/java/org/qbicc/context/CompilationContext.java
compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisInterMethodAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java

Separate the notion of an invokable method and a dispatchable method in reachability analysis.
Fixes #1143.  In theory this could have reduced the number of reachable methods, in practice it did not.  Remains to be seen if it will have more impact when we switch to a more precise reachability algorithm than RTA.

Reachability improvements

---

plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java

Only consider static fields that are actually accessed in reachable code
as roots for tracing the build time heap to identify instantiated types.
This replace a more conservative approach in which all static fields
of initialized types were considered as heap roots.

Reachability improvement for static fields

---

compiler/src/main/java/org/qbicc/context/ClassContext.java
compiler/src/main/java/org/qbicc/type/definition/DescriptorTypeResolver.java
compiler/src/main/java/org/qbicc/type/definition/ParameterResolver.java
compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFileImpl.java
compiler/src/main/java/org/qbicc/type/definition/element/InvokableElement.java
compiler/src/main/java/org/qbicc/type/definition/element/LocalVariableElement.java
compiler/src/main/java/org/qbicc/type/definition/element/ParameterElement.java
compiler/src/main/java/org/qbicc/type/definition/element/VariableElement.java
compiler/src/main/java/org/qbicc/type/generic/ArrayTypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/BaseTypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/ClassTypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/NestedClassTypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/ReferenceTypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/ThrowsSignature.java
compiler/src/main/java/org/qbicc/type/generic/TopLevelClassTypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/TypeParameter.java
compiler/src/main/java/org/qbicc/type/generic/TypeSignature.java
compiler/src/main/java/org/qbicc/type/generic/TypeVariableSignature.java
compiler/src/main/java/org/qbicc/type/util/ResolutionUtil.java
compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
driver/src/main/java/org/qbicc/driver/BasicDescriptorTypeResolver.java
driver/src/main/java/org/qbicc/driver/ClassContextImpl.java
plugins/native/src/main/java/org/qbicc/plugin/native_/ConstTypeResolver.java
plugins/native/src/main/java/org/qbicc/plugin/native_/FunctionTypeResolver.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
plugins/native/src/main/java/org/qbicc/plugin/native_/PointerTypeResolver.java
plugins/patcher/src/main/java/org/qbicc/plugin/patcher/AccessorTypeBuilder.java
plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java

Start simplifying type resolution, by:
* Removing defunct type annotation support
* Changing `Signature` to also carry annotations (groundwork)

Type resolver simplifications

---

main/src/main/java/org/qbicc/main/Main.java

Now it is disabled when the option is missing or `--no-escape-analysis` and enabled with `--escape-analysis`.

Escape analysis should be disabled by default

---

plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java

Makes it a little easier to match the generated function back to the source declaration without needing to know the details of qbicc's  name mangling algorithm.

put Class, method name, and descriptor in comment on function definition

---

compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

The index stored on the original parameter is based on using two slots for `long`/`double` which does not apply to the final image.

Use the actual index of the parameter for debug info

---

compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java

A `checkcast` whose result is primitive (due to native type mapping) would cause all of the live primitive literals with the same value to be replaced with the literal of the new type, breaking compilation of method and function calls which are passed two integers of the same value but different types.

Fix checkcast bug with primitive values

---

plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

+ Fully split the concepts of a dispatchable method and an invokable method
+ Improvements in RTA to only track classes that are actually instantiated
(stop propagating instantiation up the class hierarchy).
+ Improvements in RTA to consider actual method lookup semantics when
deciding if a method is reachable (don't force a superclass method
that is not actually invokable to be invokable just because a subclass
that also defines an overriding method is instantiated).
+ Reduce vtable size by not allocating slots for private methods;
they will always be invoked via an invokespecial and therefore
should not need to be allocated vtable slots.

improvements in RTA / Reachability Analysis

---

plugins/native/src/main/java/org/qbicc/plugin/native_/ExternExportTypeBuilder.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java
runtime/api/src/main/java/org/qbicc/runtime/stdc/Math.java
runtime/llvm/src/main/java/org/qbicc/runtime/llvm/LLVM.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/String.java

These annotations originally used a `withName` property on the annotation. But this prevents things from having different names based on platform (see how `strerror_r` is handled for one example). This is also going to be a problem very soon when the native image starts to care about things like the start and end address of segments, which have different names based on the platform.
In conjunction with #1188 and to a lesser extent #1187, we can easily change a symbol's external name based on the usual conditional infrastructure.

Switch to using `@name` annotation for extern/export

---

main/pom.xml
main/src/main/java/org/qbicc/main/Main.java
plugins/gc/common/pom.xml
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/GcCommon.java
plugins/gc/pom.xml
pom.xml
runtime/api/src/main/java/org/qbicc/runtime/stdc/String.java
runtime/gc/heap/pom.xml
runtime/gc/heap/src/main/java/org/qbicc/runtime/gc/heap/Heap.java
runtime/gc/nogc/src/main/java/org/qbicc/runtime/gc/nogc/NoGcHelpers.java
runtime/gc/pom.xml
runtime/posix/src/main/java/org/qbicc/runtime/posix/SysMman.java

Some things are still unimplemented, but this code ensures that the heap is present when any entry point method is called, and allocates all new objects out of a single contiguous memory area, throwing OOME when no more space is available.
TODO:
- ~~More than one kind of pre-allocated OOME with a descriptive error~~ Going to skip this one for now

Initial implementation of mmap-based heap allocation

---

runtime/posix/src/main/java/org/qbicc/runtime/posix/SysMman.java

Define the symbol `_DARWIN_C_SOURCE` so we are not passing `undef` in to `mmap`.

Fix run time crash on Mac OS

---

machine/tool/llvm/src/main/java/org/qbicc/tool/llvm/LlcInvokerImpl.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleDebugInfo.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java

This at least gets the executable to record the locations of the object files for debug purposes.
After this change:
```text
$ nm -ap grepj |grep OSO
000000006230aaf0 - 03 0001   OSO /Users/david/src/java/grepj/target/native/java/lang/module/ModuleDescriptor$$Lambda$219~1.o
000000006230aaf0 - 03 0001   OSO /Users/david/src/java/grepj/target/native/jdk/internal/logger/LoggerFinderLoader$$Lambda$156~1.o
000000006230aaf0 - 03 0001   OSO /Users/david/src/java/grepj/target/native/java/security/Policy$1.o
000000006230aaf0 - 03 0001   OSO /Users/david/src/java/grepj/target/native/java/lang/invoke/LambdaForm$DMH~24.o
000000006230aaf0 - 03 0001   OSO /Users/david/src/java/grepj/target/native/java/lang/reflect/ReflectPermission.o
000000006230aaf0 - 03 0001   OSO …
```

Progress on Mac OS debug info

---

driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/Module.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/debuginfo/DIGlobalVariable.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/debuginfo/DIGlobalVariableExpression.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/DIGlobalVariableExpressionImpl.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/DIGlobalVariableImpl.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/GlobalImpl.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/ModuleImpl.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleDebugInfo.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/MemberPointerCopier.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/StaticFieldLoweringBasicBlockBuilder.java

This changes the nice-name of global variables and of methods so that they match Java syntax, to an extent anyway.
With this change Mac debug works as far as it can... however, when entering a Java frame with `lldb` you are hit with this message:
```text
This version of LLDB has no plugin for the language "java". Inspection of frame variables will be limited.
```
But it really means that inspection of *any* variables is essentially nonexistent.  So going forward, we have to decide whether to rewrite the debug info to seem like C++ or some other language, or else commit to getting support for Java debug info upstream to `lldb`.

Global variable/method debug improvements

---

plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/ConnectionGraphDotVisitor.java

To fix running with escape analysis.

Override ValueConvertLiteral in connection graph dot visitor

---

main/src/main/java/org/qbicc/main/QbiccMavenResolver.java
plugins/main/src/main/java/org/qbicc/plugin/main_method/AddMainClassHook.java

...by warning when a JAR is missing on the class path and reporting an error when the specified main class is missing. Otherwise, we happily proceed and throw an unsatisfied link error at run time.

Improve invalid usage detection

---

plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleDebugInfo.java

Fixes the problem where `opt` emits a warning and then a module gets no debug info.

Relate global variable list to GV expr, not GV

---

machine/tool/llvm/src/main/java/org/qbicc/tool/llvm/AbstractLlvmInvoker.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompiler.java

This gets around the problem that the output of these tools is fundamentally unparseable, so we are losing useful information.

Report all error output of LLVM tools as one message

---

plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleDebugInfo.java

Inspection of local variables with types seems to work OK after this in `lldb`.

Set debug language to C++ so lldb works

---

compiler/src/main/java/org/qbicc/graph/ParameterValue.java

The element to which a parameter value belongs is part of its identity; else, this causes problems for parameter substitution in the inliner.

Fix ParameterValue equals/hashCode

---

machine/tool/api/src/main/java/org/qbicc/machine/tool/CToolChain.java

If the user is telling us to use a specific C compiler, then either it works or qbicc should fail.  Don't silently allow alternative C Tool Chains to also be considered.

If CC is set in the environment, don't look for alternative compilers

---

machine/tool/clang/src/main/java/org/qbicc/machine/tool/clang/ClangToolProvider.java

Not sure if this is the cleanest fix for this, but it does solve the problem I was having.
Background, I install LLVM 13 in a Docker container with a base image of `eclipse-temurin:17-focal` via: 
`RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 13 && rm llvm.sh`
`clang -###` outputs:
```
Ubuntu clang version 13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-13/bin
```
The existing regex didn't match, which resulted in this C tool chain not being recognized as valid.

recognize clang as installed from llvm.org on Ubuntu

---

compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFile.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java

Adds an `I_ACC_EXTENDED_BITMAP` modifier which indicates that the bitmap is more than 64 bits in size.

Compute bit maps for reference fields, for use by GC

---

runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java

Fixes #1269 
Added `isMacOsAmd64` and `isMacOsArm64` build targets to separate different native registrations depending of env.
This worked locally on M1 machine. Let's see if CI `darwin/amd64` agrees.

Suffix `$INODE64` not required in darwin/aarch64

---

runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackFrameCache.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackWalker.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/MethodData.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/StackWalker.java

Because we will use it during GC, and we might not be able to allocate objects at that time.
I've been sitting on this one for a while. There will be a follow-up which updates the class library to contain the implementations of the methods which uses the stack walker API, and then another follow-up to this project to remove the corresponding intrinsics. Because of the interdependency between the projects, these have to be done as the releases are completed.
The last task then is adding `java.lang.StackWalker` support to the class library side.

Stack allocate the stack walker

---

compiler/src/main/java/org/qbicc/interpreter/Vm.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ClassObjectSerializer.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/MethodDataStringsSerializer.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ObjectLiteralSerializingVisitor.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/StringInternTableEmitter.java
runtime/main/src/main/java/org/qbicc/runtime/main/InitialHeap.java

Organize heap to get interned strings into their own .ll file.
This almost does what we want, except for a single byte[] that "leaked" from its containing String object into a java.nio.fs.UnixPath object due to the use of JavaLangAccess.getBytesNoRepl.  When serializing the heap, we found the byte[] from the UnixPath object "first" and as a result there is a single pointer from the internedString section of the heap "out" to the main heap.
It would be easy to identify when this happens and generate a root table for GC scanning (which would be tiny) when we actually get to worrying about scanning the heap roots.

put interned strings into their own .ll file

---

driver/src/main/java/org/qbicc/driver/ClassContextImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

Allows BoundMethodHandle to dynamically generate Species instances at build time.

Fixes for dynamically generating a new class at build time

---

plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java

Closes #1292 
Add missing delegate visit calls for `ParameterValue` and other literal values that were not covered until now. This will enable other dot visitors to enhance these nodes if needed.

Add missing dot node visitor delegate visit calls

---

compiler/src/main/java/org/qbicc/type/definition/element/InvokableElement.java
driver/src/main/java/org/qbicc/driver/BasicDescriptorTypeResolver.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

These fixes are enough to get a trivial app to get through to the LOWER stage (before we quit with an error because we are serializing a java.lang.Thread instance).

A few workaround for compiling a tiny Quarkus application

---

driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java

Most backends seem to allow `$` in identifiers; doing so enhances readability and simplifies debugging.

Allow `$` in identifiers

---

interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java

I should have done this easy fix a long time ago.

Eliminate one major source of "Unsupported type" errors

---

driver/pom.xml
driver/src/main/java/org/qbicc/driver/ClassPathElement.java
driver/src/main/java/org/qbicc/driver/ClassPathItem.java
driver/src/main/java/org/qbicc/driver/DirectoryClassPathElement.java
driver/src/main/java/org/qbicc/driver/Driver.java
driver/src/main/java/org/qbicc/driver/JarFileClassPathElement.java
machine/vfs/src/main/java/org/qbicc/machine/vfs/DirectoryNode.java
machine/vfs/src/main/java/org/qbicc/machine/vfs/VirtualFileSystem.java
main/src/main/java/org/qbicc/main/Main.java
plugins/vfs/src/main/java/org/qbicc/plugin/vfs/VFS.java

* Change the setup of the VFS plugin to have a separate initialize vs. get step. In the future, we may set up more directories and structure on the filesystem during this step.
* Also, create a `/qbicc/java.home/` directory which is composed of all of the files under `META-INF/java.home` in all of the boot modules.

VFS next step: mounting the JDK

---

machine/file/wasm/src/main/java/org/qbicc/machine/file/wasm/WasmObjectFile.java
machine/tool/api/src/main/java/org/qbicc/machine/tool/CToolChain.java
machine/tool/emscripten/pom.xml
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/AbstractEmscriptenInvoker.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenCCompilerInvoker.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenCCompilerInvokerImpl.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenLinkerInvoker.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenLinkerInvokerImpl.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenToolChain.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenToolChainImpl.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenToolProvider.java
machine/tool/emscripten/src/main/resources/META-INF/services/org.qbicc.machine.tool.ToolProvider
machine/tool/emscripten/src/test/java/org/qbicc/machine/tool/emscripten/TestSimpleCompile.java
machine/tool/pom.xml
main/pom.xml
pom.xml

Relates to #1279 
- add `machine/tool/emscripten`
- fix issue in `WasmObjectFile`: integers weren't correctly decoded
- allow `emcc` as a compiler name
Caveats:
1. I have cloned `tool/emscripten` from `tool/clang`. If we'd rather refactor the shared parts into an abstract class I'll do it.
2. In order to ensure that `emcc` is picked over `clang` I added the `#include <pthread.h>` line to one probe to make it fail on the `WASI` platform
3. The compiler is currently not tested (except for one test case in `machine/tool/emscripten`). It can be enabled by [setting the platform `wasm-wasi`](https://github.com/qbicc/qbicc/commit/7737fe11afdd3e9603a8915cabd5dcd203d33b2f), but currently fails
(1) it uses the system LLVM toolchain for `llc`, `opt` instead of using Emscripten's, because of the way …

WASM: Add Emscripten toolchain support

---

compiler/src/main/java/org/qbicc/graph/Value.java
compiler/src/main/java/org/qbicc/graph/literal/PointerLiteral.java
compiler/src/main/java/org/qbicc/graph/literal/ProgramObjectLiteral.java
compiler/src/main/java/org/qbicc/object/ProgramObject.java
compiler/src/main/java/org/qbicc/pointer/Pointer.java
compiler/src/main/java/org/qbicc/type/CompoundType.java
compiler/src/main/java/org/qbicc/type/PointerType.java
compiler/src/main/java/org/qbicc/type/Primitive.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/element/ExecutableElement.java
compiler/src/main/java/org/qbicc/type/definition/element/VariableElement.java

This facilitates easier method call chaining without using intermediate local variables or excessive nesting of parentheses

Add `get*Type(Class<T>)` variants

---

plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java

On the Wasm backend, we do not have StackMap information (yet), thus we are generating an invalid `ProgramModule`. We return earlier and avoid scanning through the empty iterator.

MethodDataEmitter: Return immediately when stackMapRecords is empty

---

runtime/api/src/main/java/org/qbicc/runtime/Build.java
runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java

We add `Build.Target.isWasm()` and set the `SP` size to word (32)

WASM: Allow Unwind to compile for Wasm arch

---

compiler/src/main/java/org/qbicc/graph/ReferenceHandle.java
compiler/src/main/java/org/qbicc/object/ProgramObject.java
compiler/src/main/java/org/qbicc/type/PointerType.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/ObjectAccessLoweringBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

Remove the notion of "collected pointer" and use references instead. Convert instead of casting interned strings and objects of the inital heap.

Remove collectedPointers, convert references

---

compiler/src/main/java/org/qbicc/graph/ReferenceHandle.java
compiler/src/main/java/org/qbicc/type/UnresolvedType.java
compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java

It's quite reasonable to allow programs to be compiled where a runtime
null value is allowed to flow through arguments, fields, and variables
of UnresolvedType.  Change our treatment of UnresolvedType to support
that.

Allow operations on values of UnresolvedType

---

compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java

A potential fix for #1356, but I'm not 100% positive it is correct for all possible uses of invokedynamic.
It definitely is the right right thing for the MethodHandle's created to implement lambdas which collapse their parameters  to their basicTypeSignature to minimize the number of unique lambda classes created.  I spent a fair amount of time trying to see if there was a way to inspect the MethodHandle instance returned from `linkCallSite` and determine what descriptor should be used to invoke it, but wasn't convinced I'd found anything general.
FWIW, I believe if this is wrong, then we'll get an error from `llc` because the types of the actual parameters won't match the types of the function argument.  So at some level, if we aren't 100% positive this is right, its probably ok to merge …

don't demote integral arguments to invokedynamic's method handle

---

plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
plugins/native/src/main/java/org/qbicc/plugin/native_/ExternExportTypeBuilder.java

The Wasm LLVM backend crashes when a `global` variable is declared as `common` https://github.com/llvm/llvm-project/issues/55270
However, a careful re-read of the docs seem to hint that `common` is not a valid modifier for globals *in general*:
> It is illegal for a global variable or function declaration to have any linkage type other than external or extern_weak.
https://llvm.org/docs/LangRef.html#linkage-types
This PR switches `COMMON` linkage for `EXTERNAL` for globals and exported field declarations, which lowers to `external` which seems to work with both backends (an alternative may be `WEAK` which lowers to `extern_weak`)

Always use EXTERNAL linkage for Globals

---

machine/probe/pom.xml
machine/probe/src/test/java/org/qbicc/machine/probe/TestProbes.java

This reverts commit caf45a59b1306f1483adff803794844184d3d87e. The functionality is tested elsewhere, and this test fails with platform Xcode.

Revert "WASM: Support test probe for wasm object file"

---

machine/tool/api/src/main/java/org/qbicc/machine/tool/CCompilerInvoker.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenCCompilerInvokerImpl.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenLinkerInvokerImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/linker/src/main/java/org/qbicc/plugin/linker/EmscriptenLinkStage.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompileStage.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompiler.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompilerImpl.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMDefaultModuleCompileStage.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMEmscriptenCompiler.java

Attempting to add Emscripten support to the main flow.
if `isWasm`:
- use `SIMPLE` reference pointers #1352 #1355 
- use `LLVMEmscriptenCompiler` instead of `LLVMCompilerImpl` (add LLVMCompiler interface and `LLVMCompiler.Factory`
- use `LLVMEmscriptenLinkStage` (goes through `emcc` instead of `ld`)
A lot of parameters are being hardcoded both in the linker and the compiler for now. Notably:
- `-s USE_ZLIB` so that `#include<zlib.h>` works
- `-pthread` is being ignored
- `libgcc_s` and `libunwind` are being ignored in the linker because support to exceptions has to be further investigated
- compilation still needs `-fwasm-exceptions` to finish
it is possible to run the test cases via node using the following commit https://github.com/evacchi/qbicc/commit/b982156c8715242e8daaf23b3df3266b882 …

Add Emscripten support to linker and llvm module. Add branches to Main

---

plugins/graalvm-nativeimage-emulation/pom.xml

Reverts qbicc/qbicc#1351
changes internal APIs.  Need to keep matching the version used by Quarkus for its AutoFeature.

Revert "Bump svm from 21.3.0 to 22.1.0.1"

---

runtime/gc/heap/src/main/java/org/qbicc/runtime/gc/heap/Heap.java

`Heap#initHeap` is now explicitly invoked in the classlib's CMain.

Remove deprecated implicit Heap#ctor

---

compiler/src/main/java/org/qbicc/interpreter/Vm.java
compiler/src/main/java/org/qbicc/pointer/Pointer.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
main/src/main/java/org/qbicc/main/Main.java
plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java

This progresses initialization a little farther. This change had to deal with two issues.
- Scheduling issue: we're doing pointer arithmetic on nodes which cannot be understood during interpretation. Originally my plan was to rework the scheduler to be smarter about delaying nodes, but this is a can of worms so it must be done incrementally and will take long enough that it's not acceptable for it to be a blocker for this. Instead, arithmetic on invalid pointers in the interpreter always yields a null pointer.
- Now the bad news: some of these invalid pointers are being used during interpretation, which is *not* expected (because memory accesses are ordered nodes and thus should never be moved outside of their conditionals, at least with the current scheduler). Because of this I'm making …

Phase 2 initialization with module setup

---

plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java

Bug fix in reachability analysis.  When a type becomes reachable,
we must trace its java.lang.Class instance as a heap root.

the VmClass of a reachable type is a heap root

---

machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenCCompilerInvokerImpl.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenLinkerInvokerImpl.java
plugins/core/src/main/java/org/qbicc/plugin/core/ConditionEvaluation.java
runtime/gc/heap/src/main/java/org/qbicc/runtime/gc/heap/Heap.java
runtime/unwind/src/main/java/org/qbicc/runtime/unwind/LibUnwind.java
runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java

- Configure some sensible defaults for `emcc` to compiler IR and link the Wasm+JS executable
- ~~Add Wasm to the list of Unix-like platforms~~
- Disable explicit linking of libunwind, gcc_s using `unless`
- Avoid invoking `mprotect()` during heap setup, since it is unsupported (prints a warning to stderr, causes the tests to fail)
Exceptions are still not supported (test TryCatch would fail, see also https://github.com/qbicc/qbicc/pull/1402)

WASM: Configure `emcc` compilation+linking flags

---

main/src/main/java/org/qbicc/main/Main.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/AbortingThrowLoweringBasicBlockBuilder.java

Current implementation of EH leverages `libunwind`; lowering to a supported EH mechanism requires a supported runtime (in general this currently means "only NodeJS" or "V8"), which makes it harder to support smaller, embeddable runtimes such as `wasmer` and `wasmtime`.
This PR lowers `throw` to `abort()` allowing to do away with `libunwind` and EH in general for the time being. While this is not ideal, it is good enough to build self-contained nontrivial programs (e.g. good for simple plugin extensions, such as Envoy's*).
- WASM: AbortingThrowLoweringBasicBlockBuilder, abort()s instead of throwing
- WASM: Do not try to fill the stack trace
this is a follow-up to https://github.com/qbicc/qbicc/pull/1403 but may be merged independently
(*) disclaimer: Envoy currently has further limitations …

WASM: Lower `throw` to `abort()`

---

plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java

Should resolve the `unboxLong` issue in the interpreter on wasm32

MemberResolvingBBB#checkcast: Do not truncate when `toType` is a PointerType

---

interpreter/src/main/java/org/qbicc/interpreter/memory/MemoryFactory.java
interpreter/src/main/java/org/qbicc/interpreter/memory/VarHandleMemory.java

This avoids having a `ctxt` field on every single memory object.
Also introduce some constants for things that are being constructed on every method call. In particular, `Class#descriptorString` appears to do no caching.

Remove `ctxt` instance field, replace with class data entry

---

compiler/src/main/java/org/qbicc/graph/ActionVisitor.java
compiler/src/main/java/org/qbicc/graph/TerminatorVisitor.java
compiler/src/main/java/org/qbicc/graph/ValueVisitor.java

If you call the visitor parameter by the same name (lowercased) as the type or type variable, then the implementation name that is suggested will be given a name by the IDE corresponding to the resolved type argument, which is much more convenient.
This was done with regex replacement: `(T )?param` → `$1t`.

Rename visitor generic parameter

---

machine/tool/clang/src/main/java/org/qbicc/machine/tool/clang/ClangToolProvider.java

In Ubuntu 22.04, all distro clang (11+) and llc 12+ match to this format.  In Ubuntu 20.04, distro clang 11+ (i.e., 11 and 12) match to this format (though they are too old for us).

Fix version check pattern for Ubuntu distro clang

---

runtime/api/src/main/java/org/qbicc/runtime/Build.java

currently we only have an `IsWasm` property; add `isWasi` to be more specific to the rt env.
will be useful for https://github.com/qbicc/qbicc-class-library/pull/253

WASM: Add isWasi() build-time property

---

main/src/main/java/org/qbicc/main/Main.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityRoots.java
plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectiveMethodAccessorGenerator.java

In the long run, this probably should be an error, but tolerate it while
qbicc's classlib is still missing many JDK modules.

only warn when an element cannot be made reflectively available

---

runtime/api/src/main/java/org/qbicc/runtime/Build.java

Allows to opt-out of PThreads support if that is not available (currently only Wasm is affected)
(this can be rebased on #1435 if it makes more sense to use `isWasi()` instead)

Add isPThreads() build-time property

---

main/src/main/java/org/qbicc/main/Main.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMDefaultModuleCompileStage.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMGenerator.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java

The latest version of the [wasi-sdk (v16, llvm 14)](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-16) complains loudly when this attribute is present, because it is not really supported (it will abort the build).
This patch adds a boolean `gcSupport := !isWasm` (for now) that is threaded through the stack to LLVMGenerator that simply won't set `gc "example-statepoint"`. 
(I do know this may be misleading, suggestions welcome)

WASM: do not emit `gc "example-statepoint"` when isWasm

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java

Introduced by mistake with #1416

Fix wrong default intrinsics for j.l.Throwable

---

runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

it may change to `Build.Target.isPThreads()` if #1436 is merged

WASM: JLT#start0 early return instead of pthread_create()

---

plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java

If we invoke a method reflectively in the interpeter that returns
a primitive, we need to hyperbox that primitive so to conform to the
signature of Method.invoke (which returns Object).

hyperbox primitive results of reflective method invokes

---

plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnnotationTypeBuilder.java
runtime/api/src/main/java/org/qbicc/runtime/ReflectivelyAccessedElement.java
runtime/api/src/main/java/org/qbicc/runtime/ReflectivelyAccesses.java

Add annotations to allow a class to indicate that it will reflectively
access fields, methods, and constructors defined in other
classes. This complements the existing @ReflectivelyAccessed
annotation which allows annotating an element "in place" as being
reflectively accessed.

Annotations to register reflective access to other elements

---

plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java

Since some native methods' implementations are given by the `$_native` class in the qbicc-class-library, it looks fine to fill proper entries in vtables. `Runtime$_native` methods can be invoked with this change.

Fix vtable entry for the native method that has its implementation

---

pom.xml

jboss-logging 3.5 is not compatible with slf4j 2.0.0

revert slf4j back to 1.7.x

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
runtime/main/src/main/java/org/qbicc/runtime/main/CompilerIntrinsics.java
runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java

This is a follow up to #1459 to remove the code that is no longer needed once we switch to a non-intrinsic Thread.start0.
Fixes #1461 
Posting as a draft for now, will rebase and convert to non-draft once we get through all the preconditions to make it mergable.

remove obsolete thread intrinsics and support code

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java

This will make more sense in the context of the rest of my PRs...
Basically to get shutdown hooks working properly, I needed to relocate the last remnants of pthread support code from VM and VmHelpers to the class library.  Having it in one place should also make it less painful to evolve going forward.

compatibility kludge to allow relocation of qbicc_bound_thread field

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

A quick patch to avoid some NPEs at build time.
This does have the side-effect of all serialized thread instances will have the AppClassLoader as their CCL. If we want to prevent this, we could add a compensating hack of setting their CCLs to null during serialization.

use AppClassLoader as Thread.contextClassLoader in interpreter

---

main/src/main/java/org/qbicc/main/Main.java
plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/FeatureProcessor.java
plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccLocalizationFeature.java
plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccLocalizationSupport.java
plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccResourcesRegistry.java

Stub out enough additional pieces of the emulation layer that Quarkus's generated Feature can now be completely executed at build time without raising any errors.

Extend GraalVM emulation layer

---

runtime/gc/heap/src/main/java/org/qbicc/runtime/gc/heap/Heap.java

The theory here is that the destructor runs once the main thread exits, even if other threads are running, resulting in SIGSEGV for memory that was valid heap only moments before. The proper fix will probably involve blocking the destructor until all other threads have exited, potentially forcing daemon threads to terminate abruptly first.

Disable destructor

---

main/pom.xml
main/src/main/java/org/qbicc/main/Main.java
plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/GraalFeatureProcessor.java
plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccRuntimeClassInitializationSupport.java
plugins/initialization-control/pom.xml
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/FeaturePatcher.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeature.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureProcessor.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/RuntimeInitializingTypeBuilder.java
plugins/pom.xml
pom.xml

Add the ability to provide yaml file(s) to qbicc that can be used to fine-tune build-time initialization of the application being compiled.  This leverages the same mechanisms that we use for graalvm nativeimage Features, but exposes them to the user in a more declarative fashion.
In the initial version, the only implemented feature is the ability to provide a list of classes whose initialization should be deferred to runtime.

plugin for processing a qbicc build feature

---

interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
plugins/patcher/src/main/java/org/qbicc/plugin/patcher/ClassContextPatchInfo.java
plugins/patcher/src/main/java/org/qbicc/plugin/patcher/PatchedTypeBuilder.java

This cannot be merged until a class library that includes https://github.com/qbicc/qbicc-class-library/pull/290 has released.

enforce that RuntimeAspect fields cannot be accessed at build-time

---

compiler/src/main/java/org/qbicc/graph/ActionVisitor.java
compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/Reachable.java
compiler/src/main/java/org/qbicc/graph/SafePoint.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcBasicBlockBuilder.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

The following node types are added:
- `Reachable` - this node provides the implementation of `Reference.reachabilityFence(Object)`, by causing the given value to stay alive until at least that point
- `SafePoint` - this node represents a safepoint poll; no GC implements this (including NoGC) but this will eventually lower to e.g. a `test` instruction on the safepoint page address

Add a couple necessary nodes for GC support

---

compiler/src/main/java/org/qbicc/interpreter/VmClassLoader.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java

It is possible to define two classes with the same package and name when they are defined by different class loaders. This especially becomes true with applications that are compiled by frameworks which might define more than one class loader.
Put classes in different directories by class loader so that we don't end up clobbering same-named classes by accident.

Put classes in directories by class loader name

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/IntrinsicBasicBlockBuilder.java

The intrinsic contract is that if an intrinsic returns `null`, then it is not emitted at that call site. However, implementing this behavior for `Invoke` was overlooked.

Do not emit intrinsic which returns `null` in an `invoke` situation

---

machine/llvm/src/main/java/org/qbicc/machine/llvm/Types.java
machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/LLVM.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java

Fill in a missing bit of LLVM lowering around block types. Mostly this impacts `jsr` handling, so not very critical.

Properly handle block types in LLVM

---

compiler/src/main/java/org/qbicc/context/CompilationContext.java
compiler/src/main/java/org/qbicc/facts/Condition.java
compiler/src/main/java/org/qbicc/facts/Fact.java
compiler/src/main/java/org/qbicc/facts/Facts.java
compiler/src/main/java/org/qbicc/facts/core/ExecutableReachabilityFacts.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
driver/src/main/java/org/qbicc/driver/Driver.java
driver/src/main/java/org/qbicc/driver/Phase.java
main/src/main/java/org/qbicc/main/ElementReachableAdapter.java
main/src/main/java/org/qbicc/main/Main.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/FieldReachabilityFacts.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/InstanceMethodReachabilityFacts.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ObjectReachabilityFacts.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityFactsSetup.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/TypeReachabilityFacts.java

This is the ~~first~~ ~~second~~ final cut at tracking global field reachability.
* Tracks reads and writes of fields independently
* **New:** Introduce and use a prototype facts API as per #1109 
* New field reachability info for every phase, with the previous phase result available, by way of facts API
* ~~A first pass at deleting accesses of dead fields~~ Dead field removal omitted; this belongs in an optimization BBB after we've accounted for such things as on-heap objects, constant values, and fields whose usages are introduced in later phases
* Demonstration of how per-phase attachments are meant to be used, by way of facts API

Introduce Facts API, track field reachability

---

compiler/src/main/java/org/qbicc/graph/Node.java

Convert copying of an unscheduled node to a warning and an BlockEarlyTemination(unreachable()) to allow compilation of the rest of the program to proceed.

only warn when encountering an unscheduled node

---

main/src/main/java/org/qbicc/main/Main.java
main/src/main/java/org/qbicc/main/PlatformTypeSystemLoader.java
main/src/main/resources/bundles/wasm32-wasi-unknown-wasm/platform-type-info.yaml
main/src/main/resources/bundles/x86_64-darwin-unknown-macho/platform-type-info.yaml
main/src/main/resources/bundles/x86_64-linux-gnu-elf/platform-type-info.yaml

Add a `PlatformTypeSystemLoader` on `Main`. It looks for a `bundles/${platform}/platform-type-info.yaml` config. 
If missing, it will try to synthesize it using CProbes.
First attempt at doing this. Layout and position of the files may vary.
Other probes are a little more scattered, so I will do a separate PR for them. 
In the meantime we can get right the first few details here.
(follow up to the experiments in https://github.com/qbicc/qbicc/pull/1499, addresses part of #1493)

Offline probe results (Main)

---

main/src/main/java/org/qbicc/main/Main.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeature.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureProcessor.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/RuntimeResourceManager.java

Needs https://github.com/qbicc/qbicc-class-library/pull/305 to actually work, but should be harmless to merge independently since the code that needs the library support is only active if we feed the compiler a `qbicc-feature.yaml` that defines `runtimeResource` or `runtimeResources`.
I'll extend the ResourceLoading test snippet to include tests for this functionality after we merge both sides and get a classlib release.

qbicc-side of runtime resource support

---

compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFile.java
main/src/main/java/org/qbicc/main/Main.java
plugins/core/src/main/java/org/qbicc/plugin/core/CoreAnnotationTypeBuilder.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/StaticChecksBasicBlockBuilder.java
plugins/gc/common/pom.xml
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/AbstractMethodBasedSafePointStrategy.java
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/AbstractSafePointStrategy.java
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/GlobalFlagSafePointStrategy.java
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/NoSafePointStrategy.java
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/SafePointPlacementBasicBlockBuilder.java
plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/SafePoints.java
plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcBasicBlockBuilder.java
runtime/api/src/main/java/org/qbicc/runtime/NoSafePoint.java
runtime/api/src/main/java/org/qbicc/runtime/NoThrow.java
runtime/main/src/main/java/org/qbicc/runtime/main/SafePoint.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/JavaStackWalker.java
runtime/main/src/main/java/org/qbicc/runtime/stackwalk/StackWalker.java

This introduces an API and implementation for implementing actual safepoint probes. The simple implementation uses a single static boolean field to request a safepoint.
The actual body of the safepoint is not yet implemented.
The next step is to implement an API which allows plugins to register safepoint steps (for example, marking the thread stack for GC, or synchronizing all threads to perform a sweep/compact operation).

Introduce switchable safepoint strategy

---

runtime/main/src/main/java/org/qbicc/runtime/main/Once.java
runtime/main/src/main/java/org/qbicc/runtime/main/RuntimeInitializerRunner.java

Hide the <rtinit> internals so they don't appear in stacktraces.  Two motivations: (a) they are qbicc-internal functions and (b) these classes are not in a module, so StackTraceElement.computeFormat() explodes with a NPE if these methods actually appear in a stack trace we are trying to print.

Annotate a few more runtime methods with @Hidden

---

main/src/main/java/org/qbicc/main/Main.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/FeaturePatcher.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeature.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureProcessor.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureTypeBuilder.java

+ Add the ability to declare that fields and methods are reflectively accessed at runtime to qbicc features.
+ Move initial processing of qbicc feature very early in ADD preHook sequence so that it can apply to classes loaded during initial bootstrapping of the interpreter.

qbicc feature: add reflectiveFields and reflectiveMethods

---

plugins/lowering/src/main/java/org/qbicc/plugin/lowering/BooleanAccessCopier.java

Addresses a build issue on Wasm:
```
[ERROR] <stdin>:398: error: /usr/local/bin/emcc: value doesn't match function result type 'i1'
[ERROR] : error: /usr/local/bin/emcc:   ret i8 %L4, !dbg !816 ; null:0 bci@-1
[ERROR] : error: /usr/local/bin/emcc:       ^
[ERROR] : error: /usr/local/bin/emcc: 1 error generated.
[ERROR] emcc: error: /usr/local/bin/emcc: '/usr/local/Cellar/emscripten/3.1.21/libexec/llvm/bin/clang++ -target wasm32-unknown-emscripten -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=21 -I/usr/local/Cellar/emscripten/3.1.21/libexec/cache/sysroot/include/SDL …
```

Ensure integer types are truncated when returned from boolean functions

---

compiler/src/main/java/org/qbicc/graph/ValueHandleVisitorLong.java
compiler/src/main/java/org/qbicc/graph/ValueVisitorLong.java

Not functional, just a continuation of #1427.

Rename (missed) visitor generic parameter

---

compiler/src/main/java/org/qbicc/type/definition/classfile/BciRangeExceptionHandlerBasicBlockBuilder.java
integration-tests/src/it-in/snippets/TryCatch.pattern
integration-tests/src/main/java/org/qbicc/tests/snippets/TryCatch.java

Make sure the exception type is narrowed appropriately to the expected type when calling into exception catch handlers.

Manually narrow exception type for try/catch

---

plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

Reapply feccef31;  looks like it got dropped in the big rebase for #1563

failure mode on cmpxchg must be at least monotonic

---

compiler/src/main/java/org/qbicc/graph/Call.java
compiler/src/main/java/org/qbicc/graph/CallNoReturn.java
compiler/src/main/java/org/qbicc/graph/Executable.java
compiler/src/main/java/org/qbicc/graph/Invoke.java
compiler/src/main/java/org/qbicc/graph/InvokeNoReturn.java
compiler/src/main/java/org/qbicc/graph/PointerHandle.java
compiler/src/main/java/org/qbicc/graph/TailCall.java
compiler/src/main/java/org/qbicc/graph/ValueHandle.java
compiler/src/main/java/org/qbicc/object/Function.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

This is needed so that we know whether we have to create live value operand bundles for LLVM (and thereby add calls within such functions to the stack map file).

GC: Add is-safepoint tracking to lowered functions

---

compiler/src/main/java/org/qbicc/type/TypeSystem.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java

Fixes a problem with a C probed struct where `pragma(pack)` changes the struct layout algorithm.

disable alignment checking for C-probed members

---

plugins/native/src/main/java/org/qbicc/plugin/native_/ProbeUtils.java
runtime/api/src/main/java/org/qbicc/runtime/stdc/String.java
runtime/bsd/src/main/java/org/qbicc/runtime/bsd/Ifaddrs.java
runtime/bsd/src/main/java/org/qbicc/runtime/bsd/NetIf.java
runtime/linux/src/main/java/org/qbicc/runtime/linux/NetIf.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/ArpaInet.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/NetIf.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/NetinetIn.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/SysIoctl.java

This is enough to get the IPv4 subset of the native code for java.net.NetworkInterface.getAll() working on MacOS.

add some posix networking-related native APIs

---

compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java

Prefer to get the type of the variable being initialized from the initializer instead of the local variable entry unless the initializer is of type void (from a `auto()`). Fixes a problem with stack allocation of native arrays.

bugfix in stack allocation

---

compiler/src/main/java/org/qbicc/type/CompoundType.java
runtime/bsd/src/main/java/org/qbicc/runtime/bsd/Ifaddrs.java

Avoid requiring the hashCode of all members to be computed as part of computing the hashCode of a CompoundType.  This avoids an infinite recursion when the CompoundType is a C-struct that contains an member which is a pointer to the same type, the default idiom for defining linked data structures in C.

simplify CompoundType.hashCode to support linked structs

---

driver/src/main/java/org/qbicc/driver/BaseDiagnosticContext.java
machine/tool/api/src/main/java/org/qbicc/machine/tool/process/LimitedAppendable.java
machine/tool/llvm/src/main/java/org/qbicc/tool/llvm/AbstractLlvmInvoker.java

It's just fixed at 100 for now, we can make it an option later though.

Limit errors from `llc` to 1536 characters, and cap errors and warnings by default

---

main/src/main/java/org/qbicc/main/QbiccMavenResolver.java

This is for the Quarkus plugin. Also worth considering would be isolating the Maven parts to a separate module.

Make parts of QbiccMavenResolver public

---

compiler/src/main/java/org/qbicc/graph/BlockParameter.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/type/definition/classfile/ClassMethodInfo.java

When merging LVT entries, we were always applying signatures to the first entry instead of the corresponding entry.
Also, let's tag `BlockParamater` with line & bci info.

Fix wrong var signature issue

---

compiler/src/main/java/org/qbicc/interpreter/Vm.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
main/pom.xml
main/src/main/java/org/qbicc/main/DefaultArtifactRequestor.java
main/src/main/java/org/qbicc/main/Main.java
plugins/pom.xml
plugins/source/pom.xml
plugins/source/src/main/java/org/qbicc/plugin/source/SourceEmittingElementHandler.java
pom.xml

This PR gathers any resolved source JARs from the Maven resolution path and creates an output directory which contains all of the reachable source files.  You would then point the debugger to that directory with a single command, e.g. `(gdb) directory target/src`, and then you'd have complete source available.
The one problem is that we are not presently fetching source JARs during Maven artifact resolution, so I'm putting this into draft until there is occasion to fix that.
A future enhancement would be to also modify the non-Maven class path item specification function to support source directories, perhaps using some kind of magical syntax e.g. an `--app-path-source-file` which would use classpath syntax to add source paths for the application class path.
Another (much later) future …

Add ability to emit source files for debugging

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/BuildIntrinsics.java
runtime/api/src/main/java/org/graalvm/nativeimage/ImageInfo.java

I was hoping to avoid defining the stub class, but we insist on loading it before we see if a static method is an intrinsic.  The alternative would be to put the real Graal jar file in the class path,  but that seems even less desirable than this kludge.

stub out GraalVM's ImageInfo class for Quarkus 2.14

---

compiler/src/main/java/org/qbicc/graph/AbstractValue.java

Having the node name on the output is often distracting and makes things harder to read, not easier.

Tidy up `toString` for values

---

machine/tool/api/src/main/java/org/qbicc/machine/tool/LinkerInvoker.java
machine/tool/api/src/main/java/org/qbicc/machine/tool/ToolInvoker.java
machine/tool/clang/src/main/java/org/qbicc/machine/tool/clang/AbstractClangInvoker.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/AbstractEmscriptenInvoker.java
machine/tool/emscripten/src/main/java/org/qbicc/machine/tool/emscripten/EmscriptenLinkerInvokerImpl.java
machine/tool/gnu/src/main/java/org/qbicc/machine/tool/gnu/AbstractGccInvoker.java
machine/tool/llvm/src/main/java/org/qbicc/tool/llvm/AbstractLlvmInvoker.java
machine/tool/llvm/src/main/java/org/qbicc/tool/llvm/LlvmObjCopyInvokerImpl.java
plugins/linker/src/main/java/org/qbicc/plugin/linker/LinkStage.java

Workaround problems with long linker command lines by using paths relative to the tool's working directory for the input object files.

use relative paths for input files to linker command

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/BuildIntrinsics.java
runtime/api/src/main/java/org/graalvm/nativeimage/ImageInfo.java

1. Quarkus also expects inImageRuntimeCore
2. Simplify implementation by using Build.isHost/isTarget

ImageInfo fixes

---

plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/FeaturePatcher.java
plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureTypeBuilder.java
plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityRoots.java
plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java

If a class has been registered for some reflective operations, then ensure its annotationData is generated at build time so that we can support runtime reflection over its annotations.

Make annotations available at runtime for reflective classes

---

plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureTypeBuilder.java

Eager loading here violates the protocol used by qbicc to deal with cyclic type references.

bug fix: must defer loading defined type to a separate task

---

compiler/src/main/java/org/qbicc/context/CompilationContext.java
compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
driver/src/main/java/org/qbicc/driver/Driver.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

* Change `CompilationContextImpl` to use a builder since the argument list is so long
* Add initial support for the platform class loader
* Handle all "special" class loaders identically

Add support for resource loading from any class loader

---

runtime/api/src/main/java/org/qbicc/runtime/CNative.java

The intent was to use try-with-resources for stack reclamation, however this idea is too difficult to integrate with the unstructured nature of basic blocks.

Delete `close` method from `object`

---

plugins/layout/src/main/java/org/qbicc/plugin/layout/ObjectAccessLoweringBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompilerImpl.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

The difference is mostly whitespace so [ignore whitespace](https://github.com/qbicc/qbicc/pull/1685/files?diff=unified&w=1) for an easier review.

Correctly handle LLVM pointer-backed references

---

interpreter/src/main/java/org/qbicc/interpreter/impl/HooksForClass.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java
plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectiveElementRegistry.java

These are the last few fixes needed to get `graph-bfs` from knative-quarkus-bench working.  Which means that at least basic Jackson serialization of POJOs is working too....

Reflection fixes and improvements

---

plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DevirtualizingBasicBlockBuilder.java

When optimizing an invokeinterface into an invokevirtual, we still need to use the builders to generate a proper invokevirtual sequence because the method we resolved the interface invocation to may still be overriden (or abstract). Fixes a bug exposed by quarkus-vertx.

bug fix in interface to virtual dispatch optimization

---

runtime/linux/src/main/java/org/qbicc/runtime/linux/Stdlib.java

Works around what appears to be a codegen bug where it appears the stack-allocated _Float[64] array whish is the argument is being exploded at the callsite causing a mismatch in function type.

use ptr<_Float64> instead of _Float64[] to avoid bug

---

plugins/correctness/src/main/java/org/qbicc/plugin/correctness/DeferenceBasicBlockBuilder.java

The code was mistakenly appending the resolved dereference codes to a copy of the original argument array, thus in effect rewriting the call to take 2x as many arguments!

bug fix in lazy resolution of deref in call argument list

---

runtime/posix/src/main/java/org/qbicc/runtime/posix/NetIf.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/SysIoctl.java

All of these definitions are in sys/ioctl.h, so we need to put them in the right file so that constant() will work as intended.

bug fix: SIO constants declared in wrong "header" file

---

plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeTypeResolver.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java

Allows an easier way to cast between references and other word types for GC code.

Add `reference`, a word-view of an object reference

---

compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java

We're generating the right code (throw a reasonable exception at runtime) and this error is "expected" and harmless when compiling netty due to optional dependencies.

Silence bootstrap method handle warning

---

plugins/native/src/main/java/org/qbicc/plugin/native_/FunctionTypeResolver.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java
runtime/main/src/main/java/org/qbicc/runtime/main/CompilerIntrinsics.java
runtime/posix/src/main/java/org/qbicc/runtime/posix/PThread.java

Generic type inference of functional interfaces for function pointers is still a bit screwy. We can reduce complexity by just removing support for generic function invocation interfaces.
Also, deprecate all of the special pointer-form methods and classes from `Pthread`, replacing them with `ptr`-based methods.

Deprecate pointer-form classes and methods; introduce non-generic pthread start function interface

---

main/src/main/java/org/qbicc/main/MavenFriendlyConsoleHandler.java
main/src/main/resources/logging.properties

Gets rid of the warnings that Maven prints about overwriting the native output streams.

Use a Maven-friendly logging handler by default

---

compiler/src/main/java/org/qbicc/graph/AbstractNode.java
compiler/src/main/java/org/qbicc/graph/BasicBlock.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/Unschedulable.java
compiler/src/main/java/org/qbicc/graph/schedule/Scheduler.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

Add statepoint relocations so that the variable locations of references appear in the stack map where they can be parsed. Required significant rework of control flow in the LLVM node visitor in order to schedule the relocation calls.
Note that the relocated values are not actually used; the relocations are required in order to force LLVM to record the information in the stack map. There are some transformations possible in LLVM that would not work correctly without using the relocated values in place of their originals; but in these cases, we could conceivably just disable those passes via command line switches.

Statepoint relocations

---

plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java

We need to increment before we compare that the new index is in bounds, not after.
Closes #1745.

Fix stack-smash due to off-by-one

---

compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/MemberOfUnion.java
compiler/src/main/java/org/qbicc/graph/Node.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
compiler/src/main/java/org/qbicc/interpreter/Memory.java
compiler/src/main/java/org/qbicc/type/TypeSystem.java
compiler/src/main/java/org/qbicc/type/UnionType.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/memory/MemoryFactory.java
interpreter/src/main/java/org/qbicc/interpreter/memory/ZeroMemory.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/DeferenceBasicBlockBuilder.java
plugins/correctness/src/main/java/org/qbicc/plugin/correctness/StaticChecksBasicBlockBuilder.java
plugins/dot/src/main/java/org/qbicc/plugin/dot/Disassembler.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
plugins/native/src/main/java/org/qbicc/plugin/native_/NativeTypeBuilder.java
runtime/api/src/main/java/org/qbicc/runtime/CNative.java
runtime/linux/src/main/java/org/qbicc/runtime/linux/EPoll.java

At build time, a value of union type must contain only zero, otherwise an error will be produced. Type punning via unions is not presently allowed.

Basic support for unions

---

interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java

We can't eagerly create a MethodType instance if the type of the ExecutablElement contains an UnresolvedType as the return type or a parameter type. Return null instead and defer the error until the MethodType is actually used.

use null for MethodType that contains an UnresolvedType

---

plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/HeaderBits.java

Plugins will be able to declare a static `Key` (much like attachments) so that they can always find their header bit without having to record it in an intermediate data structure or attachment to pass from the early reservation to the later usage in intrinsics or BBBs.

More sophisticated header bit reservation scheme

---

compiler/src/main/java/org/qbicc/context/CompilationContext.java
compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
driver/src/main/java/org/qbicc/driver/Driver.java
main/src/main/java/org/qbicc/main/Main.java

The generic task-wrapper thing only has one use, so we can instead set it up as an ADD hook and allow some tasks to potentially run before the wrapper is in place.

Allow some pre-ADD hooks to run outside of a VM thread

---

runtime/main/src/main/java/org/qbicc/runtime/stackwalk/StackWalker.java

Different versions of this library use different layouts; it is best to just avoid the buggy library. The LLVM implementation is more reliable.

Remove aarch64 workaround for stack walker

---

runtime/main/src/main/java/org/qbicc/runtime/stackwalk/StackWalker.java

This allows us to walk the stacks of threads other than the current thread (though they do need to be in a safepoint).

Add `StackWalker` ctor for existing context

---

plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java

Fixes one of the failures observed in #1818.

Skip union member casts when opaque pointers are used

---

interpreter/src/main/java/org/qbicc/interpreter/impl/HooksForClass.java
interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java

This fixes the `MethodUtil` bootstrap class loader bug. That class implements a class loader which looks for a textual prefix which uses `.` separators for the class name; it was failing because we preemptively changed `.` to `/`. Instead, delay replacing until we need the internal name for our internal loaded-classes key.

Preserve class name through loadClass

---

plugins/lowering/src/main/java/org/qbicc/plugin/lowering/ByteOffsetBasicBlockBuilder.java

Some backends don't have support for typed pointer offset calculations, for example assembly, WASM, and probably a [not-so-distant future version of LLVM](https://discourse.llvm.org/t/rfc-replacing-getelementptr-with-ptradd/68699).
We can handle all of these using a single BBB.

Introduce `ByteOffsetBasicBlockBuilder` for lowering

---

compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
compiler/src/main/java/org/qbicc/graph/literal/TypeLiteral.java
compiler/src/main/java/org/qbicc/interpreter/Memory.java
compiler/src/main/java/org/qbicc/type/ReferenceType.java
compiler/src/main/java/org/qbicc/type/TypeIdType.java
compiler/src/main/java/org/qbicc/type/TypeSystem.java
compiler/src/main/java/org/qbicc/type/ValueType.java
interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
interpreter/src/main/java/org/qbicc/interpreter/memory/MemoryFactory.java
plugins/conversion/src/main/java/org/qbicc/plugin/conversion/NumericalConversionBasicBlockBuilder.java
plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleDebugInfo.java
plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/CallSiteTable.java
plugins/optimization/src/main/java/org/qbicc/plugin/opt/FinalFieldLoadOptimizer.java
plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java

This is in preparation for type literals to carry `TypeId` instances instead of `ValueType` for its values.

Rename `TypeType` to `TypeIdType`
