- docs/README.adoc
> Update readme based on user feedback

- .github/workflows/docs.yml
> Move off self-hosted for docs workflow

- machine/probe/src/main/java/org/qbicc/machine/probe/CProbe.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/ConstantDefiningBasicBlockBuilder.java
Conversation details: https://qbicc.zulipchat.com/#narrow/stream/284393-qbicc-development/topic/extend.20failure/near/239635405
> Register constant as type expected by MethodParser

- plugins/native/src/main/java/org/qbicc/plugin/native_/ConstantDefiningBasicBlockBuilder.java
https://qbicc.zulipchat.com/#narrow/stream/284393-qbicc-development/topic/extend.20failure/near/239648713
> Capture constants location from MethodParser

- docs/README.adoc
> Add the MacOS libgcc_s.dylib requirement

- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
This change adds more styles for edges and nodes, so we can visually identify their attributes.
- Use different colors for _then_ and _else_ edges from an _if_ node
- Use different colors for value and cond dependency edges
- Use thick lines for control dependency, and thin lines for data and order dependency
- Use dotted lines for order dependency, and use solid lines for data dependency
- Put colors in start, return, and exception return nodes, so we can easily identify where the graph starts and exits
> Better coloring for improving readbility of dot graph

- compiler/src/main/java/org/qbicc/graph/InsertElement.java
- compiler/src/main/java/org/qbicc/type/ReferenceType.java
- docs/ObjectModel.adoc
- integration-tests/src/it/java/org/qbicc/tests/integration/SimpleAppTest.java
- machine/file/macho/src/main/java/org/qbicc/machine/file/macho/MachOObjectFile.java
- machine/probe/src/main/java/org/qbicc/machine/probe/CProbe.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/StaticFieldLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
Mics cleanup of the code base
- Fix code listing formatting
- Remove unused imports
- Use enhanced for loop
- Simplify if-else with one line check
> Mics cleanup of the code base

- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
- driver/src/main/java/org/qbicc/driver/Driver.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTableBuilder.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTableEmitter.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/ClassInitializerRegister.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayTables.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RTAInfo.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
> RTA: improved reachability analysis for instance methods

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/IntrinsicBasicBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
> If intrinsic returns null method call was not replaced

- compiler/src/main/java/org/qbicc/graph/Node.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
> Missing dependency processing for StackAllocation node

- compiler/src/main/java/org/qbicc/graph/VirtualMethodElementHandle.java
- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFile.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- compiler/src/main/java/org/qbicc/type/definition/element/AnnotatedElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/BasicElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/MethodElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/ParameterElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/VariableElement.java
- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DevirtualizingBasicBlockBuilder.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/ThrowExceptionHelper.java
- plugins/thread-local/src/main/java/org/qbicc/plugin/threadlocal/ThreadLocalTypeBuilder.java
This partially (but not completely) addresses the problem in #552 as well.
> Introduce support for "Miranda" methods

- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotGenerator.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/TooBigException.java
- Avoid stack overflows by giving up on graphs that are too big (print a warning)
- Add missing support for `ClassInitCheck`
> Fix bugs in dot graph generation

- compiler/src/main/java/org/qbicc/graph/CheckCast.java
Looks unnecessary in the latest code.
> Remove "throws NoSuchElementException"

- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
Added a visitor for BitCastLiteral.
> Support BitCastLiteral in DotNodeVisotor

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFileImpl.java
- driver/src/main/java/org/qbicc/driver/Driver.java
> Add startMethod BasicBlockBuilder callback

- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcBasicBlockBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java
- runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
- runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java
> Use unsigned byte for array dimensions

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
I'm adding this intrinsic to resolve an UnsatisfiedLinkError for progress with object monitors.
> Runtime.availableProcessors intrinsic

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
> Correct sizeof result for class parameters

- compiler/src/main/java/org/qbicc/type/CompoundType.java
Take overall alignment into consideration when determining size of CompoundType
> Take overall alignment into consideration when determining size of CompoundType

- compiler/src/main/java/org/qbicc/type/CompoundType.java
> CompoundType members must have a name except INLINE

- machine/llvm/src/main/java/org/qbicc/machine/llvm/Types.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/LLVM.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/StructTypeImpl.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
- plugins/objectmonitor/src/main/java/org/qbicc/plugin/objectmonitor/ObjectMonitorBasicBlockBuilder.java
> Enable object monitor lowering

- examples/helloworld/hello/world/Main.java
- pom.xml
> Remove deserialization jar from example command

- docs/README.adoc
> Install maven manually on macos

- compiler/src/main/java/org/qbicc/type/BooleanType.java
- compiler/src/main/java/org/qbicc/type/FloatType.java
- compiler/src/main/java/org/qbicc/type/Primitive.java
- compiler/src/main/java/org/qbicc/type/SignedIntegerType.java
- compiler/src/main/java/org/qbicc/type/TypeSystem.java
- compiler/src/main/java/org/qbicc/type/UnsignedIntegerType.java
- compiler/src/main/java/org/qbicc/type/VoidType.java
- compiler/src/main/java/org/qbicc/type/WordType.java
- integration-tests/src/it-in/snippets/ClassLiteralTests.java
- integration-tests/src/it-in/snippets/ClassLiteralTests.pattern
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayTables.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ClassObjectSerializer.java
- runtime/main/src/main/java/org/qbicc/runtime/main/ObjectModel.java
This PR is an attempt to give java primitive types a "home".
It builds on that and creates class objects for primitive types,
and fixes few issues to make class literals for primitive types and their arrays work correctly.
> Primitive types and class literals

- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
This is probably the last batch of trivial intrinsics. Everything else will be somewhat more complex.
> More simple intrinsics

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/CmpAndSwap.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/CmpAndSwapImpl.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/op/CmpAndSwap.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/ObjectAccessLoweringBuilder.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/BooleanAccessBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/LocalVariableLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/StaticFieldLoweringBasicBlockBuilder.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/LocalMemoryTrackingBasicBlockBuilder.java
Allows a CAS to be weak or strong.
> Introduce strength to CmpAndSwap

- compiler/src/main/java/org/qbicc/graph/ByteSwap.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- plugins/conversion/src/main/java/org/qbicc/plugin/conversion/LLVMCompatibleBasicBlockBuilder.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
Slowly adding things needed for `Unsafe`.
> Fix a visitor error and add `ByteSwap`

- main/src/main/java/org/qbicc/main/Main.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/InitializedStaticFieldBasicBlockBuilder.java
Tested locally before updated with #666 and it appears to be doing something reasonable.  Posting for review, but as main is broken with --init-build-time atm, we might want to fix that before merging more --init-build-time cleverness ;)
> replace "reallyFinal" getstatics with interpreter-computed values

- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
This should cause pointers-to-functions (`AddressOf(Function*Handle)`) to be emitted as the global symbol corresponding to the function without incorrectly trying to assign it to a local first.
> Fix inconsistent GEP behavior for function pointers

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmInvokableImpl.java
It might be worthwhile from a performance perspective to JIT some of these `VmInvokable` instances into generated classes.
> Identify JIT candidates in the interpreter

- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
Fixes #751.
Wait to do reachability analysis until finish() is invoked by the BBB.
This ensures we will only analyze program constructs that are actually
reachable from the block entry in the final CFG.
> defer reachability analysis until finish is called

- compiler/src/main/java/org/qbicc/interpreter/VmClass.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
in conjunction with https://github.com/qbicc/qbicc-class-library/pull/36 implements enough of field/offset lookup to get Random's clinit to complete
> implement VmClass.getDeclaredFields

- compiler/src/main/java/org/qbicc/graph/Executable.java
- compiler/src/main/java/org/qbicc/graph/ValueHandle.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFile.java
- plugins/constants/src/main/java/org/qbicc/plugin/constants/ConstantBasicBlockBuilder.java
- plugins/core/src/main/java/org/qbicc/plugin/core/CoreAnnotationTypeBuilder.java
- runtime/api/src/main/java/org/qbicc/runtime/Build.java
The earlier rework to reachability plus the interpreter have largely eliminated wrong-platform class compilation, but finishing up constant-folded method calls here puts the last nail in.
> Complete constant folding support

- main/src/main/java/org/qbicc/main/Main.java
This should fix the problem of compiling a main class in a JAR.
> Correctly support JAR class path elements

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/FunctionHandle.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/VaArg.java
- compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
- compiler/src/main/java/org/qbicc/object/Function.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/LLBuilder.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/BuilderImpl.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/VaArg.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMIntrinsics.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/ExternExportTypeBuilder.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
- runtime/llvm/src/main/java/org/qbicc/runtime/llvm/LLVM.java
Completes some missing vararg support. Fix a bug which prevents `@undef` from working properly. A few other minor cleanups.
> Miscellaneous backend fixes and `va_arg` support

- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/literal/ByteArrayLiteral.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- runtime/api/src/main/java/org/qbicc/runtime/CNative.java
This makes it possible to call `printf` (varargs calling still has a problem or two though, but for now you can just do `printf(utf8z("Hello there\n"));`).
> Add utf8z (String to UTF-8 bytes) utility method

- runtime/linux/src/main/java/org/qbicc/runtime/linux/Futex.java
- runtime/linux/src/main/java/org/qbicc/runtime/linux/SysSyscall.java
- runtime/posix/src/main/java/org/qbicc/runtime/posix/PThread.java
First step towards getting `park`/`unpark` going on Linux (and now Mac too).
> Introduce futex support on Linux and POSIX condition support

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/LLVM.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/NamedGlobalValueOf.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/NamedLocalValueOf.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
This fixes a class loading error where the array classes are not found.
> Register arrays at their correct names

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmPrimitiveClassImpl.java
> Return simpleName for getName in VmPrimitiveClassImpl

- main/src/main/java/org/qbicc/main/Main.java
Fixes a problem where more than one of a given class path option cannot be given.
> Fix multiplicity of class path options

- compiler/src/main/java/org/qbicc/graph/CmpAndSwap.java
- compiler/src/main/java/org/qbicc/type/CompoundType.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
Unions do not and never have worked; I intend to introduce a new `UnionType` with a different LLVM lowering strategy at some point in the future.
I've also unified the ideas of `INLINE` structures and anonymous structures.
> Fix up composite types a bit

- compiler/src/main/java/org/qbicc/type/definition/element/AnnotatedElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/BasicElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/ConstructorElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/FieldElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/FunctionElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/GlobalVariableElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/InitializerElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/InvokableElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/LocalVariableElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/MethodElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/NestedClassElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/ParameterElement.java
- compiler/src/main/java/org/qbicc/type/definition/element/VariableElement.java
This will be the groundwork for allowing the patcher to intercept element building
> Migrate all element builders to be interfaces

- runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java
This PR lays the groundwork for supporting `Class.isInstance`, `Class.cast`, and `Class.isAssignableFrom`.  This change was achieved largely, but not *completely*, through safe non-functional IDE refactors, so it does require a second set of eyes.
> Add VMHelpers to perform type tests purely with type_ids

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/CurrentThread.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/ValueHandleVisitor.java
- compiler/src/main/java/org/qbicc/graph/ValueHandleVisitorLong.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- plugins/constants/src/main/java/org/qbicc/plugin/constants/ConstantBasicBlockBuilder.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/LowerClassInitCheckBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/ThrowLoweringBasicBlockBuilder.java
- plugins/thread-local/src/main/java/org/qbicc/plugin/threadlocal/ThreadLocalBasicBlockBuilder.java
> Change current thread read to a value handle

- integration-tests/pom.xml
- pom.xml
> Update JUnit to 5.8.2, and centrally manage

- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeInfo.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeLayout.java
> Move native layout to native plugin

- plugins/patcher/src/main/java/org/qbicc/plugin/patcher/Patcher.java
...rather than just the first one.
> Get all patch info files

- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/StaticChecksBasicBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java
> Disallow invalid bitCasts

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
Don't need this stub; remove to prepare for real implementation in class library
> remove stub intrinsic for Array.newArray

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
This lets bootstrap get a bit farther when `VarHandle`s are involved.
> Fully dynamic implementations of arrayBaseOffset0 and arrayIndexScale0

- compiler/src/main/java/org/qbicc/type/definition/ModuleDefinitionImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmThrowableImpl.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
- pom.xml
Switch to Java 17 class libraries, and fill in the pieces needed to get CI working.
> Java 17 support

- driver/src/main/java/org/qbicc/driver/Driver.java
- driver/src/main/java/org/qbicc/driver/Phase.java
> Introduce means to query previous and current phase

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmPrimitiveClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmRefArrayImpl.java
- plugins/constants/src/main/java/org/qbicc/plugin/constants/ConstantBasicBlockBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/LowerClassInitCheckBlockBuilder.java
> MemoryAtomicityMode port for instanceof-checkcast

- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/BasicHeaderInitializer.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/BasicHeaderManualInitializer.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/ThrowLoweringBasicBlockBuilder.java
- plugins/thread-local/src/main/java/org/qbicc/plugin/threadlocal/ThreadLocalBasicBlockBuilder.java
Fixes #958.
Introduces a merge conflict with #943; I can rebase 943 and resolve after this one is merged.
> AtomicityMode cleanup for noGC plugin

- compiler/src/main/java/org/qbicc/interpreter/Memory.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/BigEndianMemoryImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/LittleEndianMemoryImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/MemoryImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmPrimitiveClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmStringImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmThreadImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmThrowableImpl.java
> replace MemoryAtomicityMode with AccessMode in interpreter

- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMIntrinsics.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
> eliminate MemoryAtomicityMode from llvm plugin

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
Fixes #961
Needs a more careful review than most of the other related PRs.  I'm making some educated guesses on the Unsafe intrinsic changes, but could easily have got something wrong.
> port intrinsics from MemoryAtomicityMode to AccessMode

- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinition.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
Doesn't reduce the error count in the end, but gets us further along into SimpleMethodHandle creation.
Not sure what `isHidden` actually should do in qbicc, but perhaps this is reasonable...
> a couple of interpreter fixes for BoundMethodHandle <init>

- runtime/api/src/main/java/org/qbicc/runtime/stdc/Errno.java
Using native types for accessors is not allowed.
> Fix errno access until #978

- docs/README.adoc
> Doc update: LLVM 13 is supported

- compiler/src/main/java/org/qbicc/interpreter/VmClass.java
- driver/src/main/java/org/qbicc/driver/Driver.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java
- plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java
- runtime/pom.xml
- runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java
- runtime/posix/src/main/java/org/qbicc/runtime/posix/Unistd.java
These were all encountered while implementing VFS/VIO.
> Miscellaneous bug fixes

- runtime/api/src/main/java/org/qbicc/runtime/stdc/Stdlib.java
- runtime/linux/src/main/java/org/qbicc/runtime/linux/Linux$_runtime.java
- runtime/linux/src/main/java/org/qbicc/runtime/linux/Linux.java
- runtime/linux/src/main/resources/qbicc-patch-info
- runtime/posix/src/main/java/org/qbicc/runtime/posix/SysUtsname.java
Define a means to test the run time Linux kernel version.
> Linux support methods

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- runtime/api/src/main/java/org/qbicc/runtime/stdc/Errno.java
- runtime/linux/src/main/java/org/qbicc/runtime/linux/Futex.java
* One last errno fix
* Fix a futex problem
* Fix spurious NPE due to missing intrinsics
> Remaining changes to fix park/unpark

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/InitCheck.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeInitManager.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InitCheckLoweringBasicBlockBuilder.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityAnalysis.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
- plugins/verification/src/main/java/org/qbicc/plugin/verification/LowerVerificationBasicBlockBuilder.java
- runtime/main/src/main/java/org/qbicc/runtime/main/CompilerIntrinsics.java
- runtime/main/src/main/java/org/qbicc/runtime/main/Once.java
- runtime/main/src/main/java/org/qbicc/runtime/main/RuntimeInitializerRunner.java
* enhance reachability analysis for ObjectLiteral
* generate rtinit check sequence
* use Once instances to implement rtinit operation
Still not working: actually invoking the rtinit from the thunk
(unimplemented intrinsic).
> progress on runtime support for <rtinit>

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java
> CNative.ptr.sel() fix

- compiler/src/main/java/org/qbicc/context/CompilationContext.java
- compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
- driver/src/main/java/org/qbicc/driver/Driver.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
- plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcSetupHook.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java
> improve reachability analysis of runtime functions and dispatch tables

- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/BasicHeaderInitializer.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/BasicHeaderManualInitializer.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/VMHelpersSetupHook.java
- plugins/objectmonitor/src/main/java/org/qbicc/plugin/objectmonitor/ObjectMonitorBasicBlockBuilder.java
- runtime/main/src/main/java/org/qbicc/runtime/main/CompilerIntrinsics.java
- runtime/main/src/main/java/org/qbicc/runtime/main/VMHelpers.java
Requires a release of qbicc-class-library including qbicc/qbicc-class-library#78.
> Use non-native monitors

- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
> Unbox booleans as ints upon request

- runtime/posix/src/main/java/org/qbicc/runtime/posix/SysStat.java
- runtime/posix/src/main/java/org/qbicc/runtime/posix/SysTypes.java
Might need classlib release... Update: it doesn't
> Remove duplicate time_t

- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
Eliminates many errors that arise from platform-specific code
> Do not parse unreachable bytecode

- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBasicBlockBuilder.java
Sometimes layouts get confused and other weird things happen when using alias members in a `$_native` class.  This cleans up those problems making it more reliable to have fields, methods, and constructors in a `$_native` class which alias the originals.
> Fix problem with resolving aliased native members

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
This should solve ULEs relating to `Unsafe#getShort` and a few others.
> Add some more Unsafe intrinsics

- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
Solves a bug where auto-queued elements can potentially be replicated resulting in duplicate function errors
> Ensure that all members are only ever resolved once

- plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java
This is not a functional change.
> Refactor helper methods to instanceof pattern matches

- compiler/src/main/java/org/qbicc/graph/ActionVisitor.java
- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DebugValueDeclaration.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- compiler/src/main/java/org/qbicc/type/definition/element/LocalVariableElement.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/DotNodeVisitor.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
And lay the groundwork for optimizing local variables into registers... this makes `info args` work in `gdb`.
> Recognize function arguments in the debugger

- machine/arch/src/main/java/org/qbicc/machine/arch/Cpu.java
- machine/tool/gnu/src/main/java/org/qbicc/machine/tool/gnu/GnuToolProvider.java
- runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java
Compilation still doesn't complete on ARM 32-bit, but at least it can find the compiler.  There are remaining problems in the layout and possibly interpreter plugins.
> A few ARM 32-bit fixes

- compiler/src/main/java/org/qbicc/interpreter/Vm.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFile.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
* Improve performance by calling the bootstrap method directly instead of via interpreter
* Fix incorrect argument values to the bootstrap method
* Fix handling of vararg bootstraps
> Fix MH bootstrap invocation

- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFileImpl.java
- compiler/src/main/java/org/qbicc/type/generic/ArrayTypeSignature.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
- plugins/patcher/src/main/java/org/qbicc/plugin/patcher/PatchedTypeBuilder.java
Make them available to LoadedTypeDefinition
> Nestmates support part 2 & 3

- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RapidTypeAnalysis.java
Because we are building "classic" class-based vtables, if an
instance method of a class that overrides a superclass method
is invokable, we have to consider the superclass method invokable
(even if it is never invoked at the superclass static type). This
ensures a compatible vtable layout for all related classes/methods.
> fix invokability definition for superclass methods

- compiler/src/main/java/org/qbicc/graph/PhiValue.java
- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcBasicBlockBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InitCheckLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
- plugins/main/src/main/java/org/qbicc/plugin/main_method/UserMainIntrinsic.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectionIntrinsics.java
Method handles are still dispatching on null pointers, but this brings us closer. Almost all method handles are being produced now, with only a couple of exceptions.
> Further method handle work

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
Requires qbicc/qbicc-class-library#91
> Provide the initial host environment

- plugins/verification/src/main/java/org/qbicc/plugin/verification/MemberResolvingBasicBlockBuilder.java
(Even if the method is in a hidden class)
> Recognize self descriptor in `new_`

- plugins/core/src/main/java/org/qbicc/plugin/core/ConditionEvaluation.java
This should allow (some) conditional annotations to be used on early types like `java.lang.Object`.
> Add predefined results for certain conditional annotation values

- compiler/src/main/java/org/qbicc/type/ClassObjectType.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectionIntrinsics.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/VarHandleResolvingBasicBlockBuilder.java
This should help alleviate the reachability problem described in #1192.
> Implement `VarHandle` using virtual method dispatch

- runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java
This was originally necessary because the pointer manipulations were not all correct, but it should work now.
> Remove heap allocation in stack unwinder

- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
Fixes a problem where we are encoding the character for `.` rather than using a single `_` for a `/`. Also neatens method descriptor encoding.
> Another improvement on debug names

- .github/workflows/maven.yml
- docs/README.adoc
- main/src/main/java/org/qbicc/main/Main.java
- plugins/linker/src/main/java/org/qbicc/plugin/linker/LinkStage.java
- runtime/unwind/src/main/java/org/qbicc/runtime/unwind/Unwind.java
I suspect this may fail, due to `libgcc_s`, but TIAS I guess.
> Run CI on Mac OS as well

- pom.xml
- runtime/api/src/main/java/org/qbicc/runtime/stdc/Stdio.java
> Use alt. names for streams on Mac OS

- plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/ConnectionGraph.java
* `ParameterValue` now takes element into account when computing equals (since https://github.com/qbicc/qbicc/pull/1225). This means that for interface or abstract/overriden method calls, multiple instances exist for the same parameter index slot.
* If any of them escapes globally, that information needs to be propagated to other `ParameterValue` instances for escape analysis to work as expected.
* Method exit is a good place to add this, because it already takes care of propagating global escape information.
* The fix extends this propagation to other `ParameterValue` instances.
> Propagate interface/abstract method escape analysis

- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinition.java
> Fix `hasNoModifiersOf`

- main/src/main/java/org/qbicc/main/Main.java
- plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/MultiNewArrayExpansionBasicBlockBuilder.java
> Move MultiNewArrayBasicBlockBuilder to GC Common plugin

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmRefArrayClassImpl.java
This is temporary until we have a new initial heap setup procedure.
> Work around nest host mismatching problems

- compiler/src/main/java/org/qbicc/type/TypeSystem.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/DataLayout.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/Module.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/SymbolMangling.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/DataLayoutImpl.java
- machine/llvm/src/main/java/org/qbicc/machine/llvm/impl/ModuleImpl.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java
> Add datalayout string to LLVM output

- machine/arch/src/main/java/org/qbicc/machine/arch/ABI.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Cpu.java
- machine/arch/src/main/java/org/qbicc/machine/arch/ObjectType.java
No support is added, just the constants.
> Add constants for WASM

- compiler/src/main/java/org/qbicc/context/CompilationContext.java
- compiler/src/main/java/org/qbicc/graph/ClassOf.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
- plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java
- plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodInfo.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ClassObjectSerializer.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/ObjectLiteralSerializingVisitor.java
- runtime/main/src/main/java/org/qbicc/runtime/main/InitialHeap.java
Doing a CI test to verify I'm headed down a plausible path; not really ready to merge yet.
> generate flat class array

- compiler/src/main/java/org/qbicc/interpreter/Vm.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/StringInternTableEmitter.java
- runtime/main/src/main/java/org/qbicc/runtime/main/InitialHeap.java
First cut at the build-time side of  #1267.
> InitialHeap.internedStrings contains array of build-time interned Strings

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
Gets rid of a couple more assertion errors.
> More nest host fixes

- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/Lowering.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/StringInternTableEmitter.java
Finishes the build-time side of #1267
> Finish build time side of String interning

- compiler/src/main/java/org/qbicc/pointer/Pointer.java
- compiler/src/main/java/org/qbicc/type/definition/element/VariableElement.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmInvokableImpl.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
Fix a couple bugs that showed up while working on #1266.  Program isn't working yet...but hopefully getting closer.
> progress towards lambda form for String concatenation working

- plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisIntraMethodBuilder.java
Fixes #1172 
If new allocations get passed to a call that is returned, at the method level we can't guarantee that they don't escape. So, make sure those are marked for tracking as argument escape.
> Track non-primitive args to calls returned #1172

- main/src/main/java/org/qbicc/main/Main.java
- runtime/zlib/src/main/java/org/qbicc/runtime/zlib/ZLib.java
Forgot to load the library, and also didn't make it available to `main` so you'd get an error.
> Fix a couple zlib problems

- main/src/main/java/org/qbicc/main/Main.java
Add --jar <executableJar> command line argument and process jar file
to extract Main-Class and Class-Path attributes.
> Support for compiling an executable jar

- machine/file/wasm/src/main/java/org/qbicc/machine/file/wasm/kaitai/Webassembly.java
Update to https://github.com/evacchi/kaitai-webassembly/commit/8c6b25905aeaf9ccaf5c96987dd8d621e7d536a4
> WASM: Update Kaitai Wasm parser to current HEAD

- compiler/src/main/java/org/qbicc/context/CompilationContext.java
- compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
- docs/README.adoc
- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
- driver/src/main/java/org/qbicc/driver/Driver.java
- integration-tests/src/it/java/org/qbicc/tests/integration/utils/Qbicc.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/main/src/main/java/org/qbicc/plugin/main_method/AddMainClassHook.java
This does not yet cover the following cases:
* Loading classes via `Class.forName()` or `appCl.loadClass()`
* Loading resources from the application class path
These would be done with additional invokers/intrinsics and we should probably have a story for how we want to bundle resources into the image before we go to that point.
> Run programs from the application class path

- .github/workflows/docs.yml
- .github/workflows/maven.yml
- maven-plugin/src/main/java/org/qbicc/maven/plugin/QbiccCompileMojo.java
> Use matrix to build with different LLVM versions

- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectionIntrinsics.java
Fixes many CNFE raised by the MethodHandle intrinsics because types
loaded by the AppClassLoader are not findable from the
bootstrapClassContext.
> Use the classContext of the MethodElement to build MethodType

- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleDebugInfo.java
> map the Unresovled type to void* in debug info

- machine/arch/pom.xml
- machine/arch/src/main/java/org/qbicc/machine/arch/ArmCpu.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Cpu.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Register_AArch64.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Register_ARM.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Register_None.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Register_x86.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Register_x86_64.java
This will help with GC and making sense of stack maps.
> Add DWARF register numbers and names to CPU information

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- main/src/main/java/org/qbicc/main/Main.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityInfo.java
- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/RuntimeReflectionRoots.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java
- runtime/api/src/main/java/org/qbicc/runtime/ReflectivelyAccessed.java
Progress towards https://github.com/qbicc/qbicc/issues/1383
Needs https://github.com/qbicc/qbicc-class-library/pull/238
> Initial cut at runtime reflection support

- compiler/src/main/java/org/qbicc/pointer/Pointer.java
- compiler/src/main/java/org/qbicc/type/ArrayType.java
- compiler/src/main/java/org/qbicc/type/PrimitiveArrayObjectType.java
- compiler/src/main/java/org/qbicc/type/ReferenceArrayObjectType.java
- compiler/src/main/java/org/qbicc/type/TypeSystem.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
But, fix some of the bugs we met along the way.
> Disable phase 2 init for now

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmStringImpl.java
Two problems:
1. The string byte array is *always* little-endian, even on big-endian systems
2. The `UTF16LE` charset may replace characters it deems to be invalid, but some hacky bits of the JDK use Strings as a general-purpose 16-bit integer array which can jam this up
> Avoid corruption of "contents" view of `VmStringImpl`

- runtime/gc/heap/src/main/java/org/qbicc/runtime/gc/heap/Heap.java
mmap, munmap, mprotect are all unsupported calls on WASI, we fallback to a trivial strategy for now
(uses `isWasm`, it probably makes more sense to leverage `isWasi` #1435 because emscripten currently works by emulating them)
> WASM: Do not mmap, malloc a fixed 1G heap

- plugins/core/src/main/java/org/qbicc/plugin/core/ConditionEvaluation.java
> Add `IsPThreads` and `IsWasi` to `ConditionEvaluation`

- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/ReachabilityBlockBuilder.java
Lambda instances are instantiated via Unsafe.allocateInstance,
so reachability analysis can't depend on seeing a `New` for
every type that is instantiated.  Work around this by recognizing
invokes to `<init>` that aren't from a `super.<init>` and
marking the declaring type of the `<init>` as being instantiated.
> reachability fix for lambdas

- compiler/src/main/java/org/qbicc/type/annotation/Annotation.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmThrowableImpl.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/ThrowExceptionHelper.java
- plugins/verification/src/main/java/org/qbicc/plugin/verification/ClassLoadingBasicBlockBuilder.java
Gets us down to under 150 warning messages.  Generated program still crashes, but compilation is getting a little less noisy...
> four small fixes for quarkus

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
Add some utilities to `BasicBlockBuilder` to simplify life a little bit.
> Add useful utilities to BasicBlockBuilder

- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
For no-throw functions and methods, throwing an exception will blow up everything. So, we can remove exception-throwing checks from no-throw functions and methods without affecting the overall correctness of the program. In return we trade more expensive undefined behavior for less expensive undefined behavior, with a corresponding (slight) improvement in compile time and image size.
> Skip checks in no-throw elements

- compiler/src/main/java/org/qbicc/graph/AddressOf.java
- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/ElementOf.java
- compiler/src/main/java/org/qbicc/graph/MemberOf.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/Value.java
- compiler/src/main/java/org/qbicc/graph/ValueHandleVisitor.java
- compiler/src/main/java/org/qbicc/graph/ValueHandleVisitorLong.java
- compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
- compiler/src/main/java/org/qbicc/graph/ValueVisitorLong.java
- compiler/src/main/java/org/qbicc/pointer/MemberPointer.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/StaticChecksBasicBlockBuilder.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/Disassembler.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/ObjectAccessLoweringBuilder.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/LocalMemoryTrackingBasicBlockBuilder.java
On the path towards getting all non-`Literal` nodes on the schedule.
> Change `MemberOf` and `ElementOf` from handles to values

- plugins/reachability/src/main/java/org/qbicc/plugin/reachability/BuildtimeHeapAnalyzer.java
1. Detect pointers that have been stored in long fields.
2. StaticFieldPointers on the heap make their field reachable
> heap reachability fixes for pointers

- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
> Make sure BCI and line is set for all block nodes

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinition.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/BasicHeaderInitializer.java
- plugins/core-classes/src/main/java/org/qbicc/plugin/coreclasses/CoreClasses.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/RuntimeChecksBasicBlockBuilder.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/StaticChecksBasicBlockBuilder.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/Disassembler.java
- plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/MultiNewArrayExpansionBasicBlockBuilder.java
- plugins/gc/common/src/main/java/org/qbicc/plugin/gc/common/safepoint/GlobalFlagSafePointStrategy.java
- plugins/gc/nogc/src/main/java/org/qbicc/plugin/gc/nogc/NoGcBasicBlockBuilder.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/InstanceOfCheckCastBasicBlockBuilder.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/UnsafeIntrinsics.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/ObjectAccessLoweringBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InitCheckLoweringBasicBlockBuilder.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/InvocationLoweringBasicBlockBuilder.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/LocalMemoryTrackingBasicBlockBuilder.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/SimpleOptBasicBlockBuilder.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/ea/EscapeAnalysisOptimizeVisitor.java
- plugins/optimization/src/test/java/org/qbicc/plugin/opt/TestSimpleOptBasicBlockBuilderBooleanLogic.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/Reflection.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectionIntrinsics.java
- plugins/try-catch/src/main/java/org/qbicc/plugin/trycatch/ExceptionOnThreadBasicBlockBuilder.java
- plugins/unwind/src/main/java/org/qbicc/plugin/unwind/UnwindExceptionStrategy.java
- plugins/unwind/src/main/java/org/qbicc/plugin/unwind/UnwindThrowBasicBlockBuilder.java
Also fix some bugs found along the way.
> Clean up uses of deprecated memory op methods

- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBasicBlockBuilder.java
> Allow initializing array syntax for `auto` native types

- main/src/main/java/org/qbicc/main/Main.java
- plugins/optimization/src/main/java/org/qbicc/plugin/opt/LocalOptBasicBlockBuilder.java
- plugins/optimization/src/test/java/org/qbicc/plugin/opt/TestSimpleOptBasicBlockBuilderBooleanLogic.java
The optimizations might not always be simple, but they will always be local.
> Rename `SimpleOpt...` to `LocalOpt...`

- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
> Ensure that values stored in local vars have the right type

- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
Handle the case where the static arguments to the bootstrap method represent a mix of normal arguments and trailing varargs.
Fixes #1629.
> indy fix to support ObjectMethods.bootstrap

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/BuildIntrinsics.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
- runtime/api/src/main/java/org/qbicc/runtime/Build.java
> Replace macro usage with intrinsics

- compiler/src/main/java/org/qbicc/context/CompilationContext.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/literal/ElementOfLiteral.java
- compiler/src/main/java/org/qbicc/graph/literal/Literal.java
- compiler/src/main/java/org/qbicc/graph/literal/LiteralFactory.java
- compiler/src/main/java/org/qbicc/graph/literal/LiteralVisitor.java
- compiler/src/main/java/org/qbicc/graph/literal/MemberOfLiteral.java
- compiler/src/main/java/org/qbicc/graph/literal/OffsetFromLiteral.java
- compiler/src/main/java/org/qbicc/object/ModuleSection.java
- compiler/src/main/java/org/qbicc/object/ProgramModule.java
- compiler/src/main/java/org/qbicc/object/Section.java
- compiler/src/main/java/org/qbicc/type/definition/element/GlobalVariableElement.java
- compiler/src/test/java/org/qbicc/type/generic/TestClassContext.java
- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
- machine/arch/src/main/java/org/qbicc/machine/arch/ObjectType.java
- machine/arch/src/main/java/org/qbicc/machine/arch/Platform.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
- plugins/instanceof-checkcast/src/main/java/org/qbicc/plugin/instanceofcheckcast/SupersDisplayTables.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleGenerator.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMStripStackMapStage.java
- plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataEmitter.java
- plugins/methodinfo/src/main/java/org/qbicc/plugin/methodinfo/MethodDataTypes.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/ExternExportTypeBuilder.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
This is the start of organizing things into sections so that GC can find them. This PR organizes classes, strings, variables of reference type, and other objects into discrete sections.
Also contains some significant bugfixes with how we handle and emit literals.
> Start moving things to their proper sections

- main/src/main/java/org/qbicc/main/Main.java
- plugins/graalvm-nativeimage-emulation/pom.xml
- plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccBeforeAnalysisAccess.java
- plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccResourcesRegistry.java
- plugins/graalvm-nativeimage-emulation/src/main/java/org/qbicc/plugin/nativeimage/QbiccRuntimeClassInitializationSupport.java
- plugins/initialization-control/src/main/java/org/qbicc/plugin/initializationcontrol/QbiccFeatureProcessor.java
Enables qbicc-feature to be obtained from a jar for quarkus-qbicc.
> accept URLs for qbicc-feature.yaml

- plugins/native/src/main/java/org/qbicc/plugin/native_/Native.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeTypeResolver.java
- runtime/api/src/main/java/org/qbicc/runtime/CNative.java
Adds a type which corresponds to the type of the heap object header bits.
> Add `header_type`

- compiler/src/main/java/org/qbicc/object/ModuleSection.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- compiler/src/main/java/org/qbicc/type/definition/element/VariableElement.java
- plugins/core/src/main/java/org/qbicc/plugin/core/CoreAnnotationTypeBuilder.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
One last PR before the break ⛄
> Implement `align` for variable elements

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/PointerDifference.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/Disassembler.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMCompatibleBasicBlockBuilder.java
This will be useful when lowering compressed refs.
> Add `PointerDifference` node and missing `minus` intrinsic implementation

- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/LoadedTypeDefinitionImpl.java
This makes for somewhat less annoying debugging.
> Add `toString` for type defs

- compiler/src/main/java/org/qbicc/type/definition/element/MethodElement.java
- plugins/reflection/src/main/java/org/qbicc/plugin/reflection/ReflectionIntrinsics.java
> Sigpoly and method handle fixes

- main/src/main/java/org/qbicc/main/Main.java
> move most analyze postHooks to lower preHooks

- compiler/src/main/java/org/qbicc/type/ObjectType.java
- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinition.java
- compiler/src/main/java/org/qbicc/type/definition/DefinedTypeDefinitionImpl.java
- compiler/src/main/java/org/qbicc/type/definition/DelegatingDefinedTypeDefinition.java
- driver/src/main/java/org/qbicc/driver/CompilationContextImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassLoaderImpl.java
- plugins/dispatch/src/main/java/org/qbicc/plugin/dispatch/DispatchTables.java
- plugins/layout/src/main/java/org/qbicc/plugin/layout/Layout.java
- plugins/patcher/src/main/java/org/qbicc/plugin/patcher/ClassPatchInfo.java
> Add a digest to hidden class identifiers

- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
* Always create derefs for structure member accesses
* Convert derefs to loads when storing into a local variable
> Dereference fixes

- runtime/linux/src/main/java/org/qbicc/runtime/linux/SysIoctl.java
Probably needs a class lib release; submitting PR now so I don't forget about it...
> remove ioctl; now defined in posix.SysIoctl

- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- plugins/native/src/main/java/org/qbicc/plugin/native_/NativeBasicBlockBuilder.java
- runtime/api/src/main/java/org/qbicc/runtime/CNative.java
These are the first steps towards being able to achieve:
* Function pointers using method references
* Invocation of functions by pointer
* Lazy bootstrapping of InvokeDynamic (the goal being to only bootstrap them when the code is reachable or when the interpreter encounters them)
> Improve functional interface support

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CoreIntrinsics.java
This will expose the pure-Java ones introduced in qbicc/qbicc-class-library#388.
> Remove stack trace intrinsics

- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
This helps GC understand array layouts.
> Store size and alignment of primitive type classes

- main/src/main/java/org/qbicc/main/Main.java
Mostly whitespace so review with [this link](https://github.com/qbicc/qbicc/pull/1777/files?w=1) to see the actual changes.
> Unwrap mysterious block

- compiler/src/main/java/org/qbicc/type/definition/classfile/ClassFileImpl.java
> Do not set superclass name for interfaces

- compiler/src/main/java/org/qbicc/graph/AbstractWordCastValue.java
- compiler/src/main/java/org/qbicc/graph/BasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/DecodeReference.java
- compiler/src/main/java/org/qbicc/graph/DelegatingBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/FpToInt.java
- compiler/src/main/java/org/qbicc/graph/IntToFp.java
- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/SimpleBasicBlockBuilder.java
- compiler/src/main/java/org/qbicc/graph/ValueVisitor.java
- compiler/src/main/java/org/qbicc/graph/WordCastValue.java
- compiler/src/main/java/org/qbicc/type/definition/classfile/MethodParser.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/Frame.java
- plugins/conversion/src/main/java/org/qbicc/plugin/conversion/NumericalConversionBasicBlockBuilder.java
- plugins/correctness/src/main/java/org/qbicc/plugin/correctness/DeferenceBasicBlockBuilder.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/Disassembler.java
- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMNodeVisitor.java
> Introduce `FpToInt` and `IntToFp` nodes

- compiler/src/main/java/org/qbicc/graph/Node.java
- compiler/src/main/java/org/qbicc/graph/literal/BooleanLiteral.java
- compiler/src/main/java/org/qbicc/graph/literal/EncodeReferenceLiteral.java
- compiler/src/main/java/org/qbicc/graph/literal/FloatLiteral.java
- compiler/src/main/java/org/qbicc/graph/literal/IntegerLiteral.java
- compiler/src/main/java/org/qbicc/graph/literal/Literal.java
- compiler/src/main/java/org/qbicc/graph/literal/LiteralFactory.java
- compiler/src/main/java/org/qbicc/graph/literal/LiteralVisitor.java
- interpreter/src/main/java/org/qbicc/interpreter/impl/VmClassImpl.java
- machine/probe/src/main/java/org/qbicc/machine/probe/CProbe.java
- plugins/dot/src/main/java/org/qbicc/plugin/dot/Disassembler.java
- plugins/llvm/src/main/java/org/qbicc/plugin/llvm/LLVMModuleNodeVisitor.java
- plugins/lowering/src/main/java/org/qbicc/plugin/lowering/MemberPointerCopier.java
- plugins/serialization/src/main/java/org/qbicc/plugin/serialization/BuildtimeHeap.java
> Introduce `EncodeReferenceLiteral` and drop `ValueConvertLiteral`

- plugins/intrinsics/src/main/java/org/qbicc/plugin/intrinsics/core/CNativeIntrinsics.java
- runtime/api/src/main/java/org/qbicc/runtime/CNative.java
> Implement remaining memory movement intrinsics

- machine/file/bin/src/main/java/org/qbicc/machine/file/bin/BinaryRandomAccess.java
- machine/file/bin/src/main/java/org/qbicc/machine/file/bin/BufferBinaryOutput.java
- machine/file/bin/src/main/java/org/qbicc/machine/file/bin/BufferBinaryRandomAccess.java
- machine/file/bin/src/main/java/org/qbicc/machine/file/bin/ChannelBinaryOutput.java
This is inteded as an eventual replacement for `BinaryBuffer`.
> Introduce `BinaryRandomAccess`
